#!/usr/bin/env python3
from __future__ import annotations

import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PAYLOAD = json.loads(base64.b64decode("eyJjb21wbGV0aW9uX3NjcmlwdCI6ICIjIS91c3IvYmluL2VudiBweXRob24zXG5cIlwiXCJWYWxpZGF0ZSBleGlzdGluZyB0cmFuc2l0aW9uYWwgUmVsYXlMTSBjb21wbGV0aW9uLXJlcG9ydCBmaWxlcy5cblxuVGhpcyB2YWxpZGF0b3IgaW50ZW50aW9uYWxseSBvd25zIG5vIGRvY3VtZW50YXRpb24tbW9kZWwsIHRlbXBsYXRlLCBjdXJyZW50LXN0YXR1cyxcbmFyY2hpdGVjdHVyZSwgb3IgY29udHJhY3Qgc2VtYW50aWNzLiBJdCBwcmVzZXJ2ZXMgb25seSB0aGUgYm91bmRlZCBzdHJ1Y3R1cmFsXG5pbnRlZ3JpdHkgb2YgYWxyZWFkeS1jb21taXR0ZWQgY29tcGxldGlvbiByZXBvcnRzIHdoaWxlIEQyLUQ2IGFzc2lnbnMgdGhlaXIgZmluYWwgZGlzcG9zaXRpb24uXG5cIlwiXCJcbmZyb20gX19mdXR1cmVfXyBpbXBvcnQgYW5ub3RhdGlvbnNcblxuaW1wb3J0IGFyZ3BhcnNlXG5pbXBvcnQgc3lzXG5pbXBvcnQgdGVtcGZpbGVcbmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aFxuZnJvbSB0eXBpbmcgaW1wb3J0IENhbGxhYmxlXG5cblJPT1QgPSBQYXRoKF9fZmlsZV9fKS5yZXNvbHZlKCkucGFyZW50c1sxXVxuTUFYX0JZVEVTID0gMTMxMDcyXG5SRVBPUlRfRElSRUNUT1JZID0gUGF0aChcImRvY3MvZXZpZGVuY2UvaW1wbGVtZW50YXRpb25cIilcblxuU0VDVElPTl9BTkNIT1JTID0gKFxuICAgIFwiIyMgU2NvcGVcIixcbiAgICBcIiMjIEltcGxlbWVudGVkIHByb2R1Y3Rpb24gYm91bmRhcnlcIixcbiAgICBcIiMjIFByZXNlcnZlZCBhdXRob3JpdGllcyBhbmQgbm9uLWdvYWxzXCIsXG4gICAgXCIjIyBDaGFuZ2VkIGZpbGVzXCIsXG4gICAgXCIjIyBWYWxpZGF0aW9uIGV2aWRlbmNlXCIsXG4gICAgXCIjIyBLbm93biBsaW1pdGF0aW9uc1wiLFxuICAgIFwiIyMgU2hhcmVkIGRvY3VtZW50YXRpb24gdXBkYXRlIGlucHV0c1wiLFxuICAgIFwiIyMgU291cmNlIHB1bGwgcmVxdWVzdFwiLFxuKVxuU0hBUkVEX1JFUE9SVF9BTkNIT1JTID0gKFxuICAgIFwicmVsYXlsbV9jdXJyZW50X3N0YXR1c19zb3VyY2U6IC4uLy4uL1BST0pFQ1RfU1RBVFVTLm1kXCIsXG4gICAgXCJyZWxheWxtX3NvdXJjZV9wcjpcIixcbiAgICBcInJlbGF5bG1fcmVjb3JkZWRfb246XCIsXG4pICsgU0VDVElPTl9BTkNIT1JTXG5cbkxFR0FDWV9QUk9GSUxFID0ge1xuICAgIFwicmVsYXlsbV9kb2NfdHlwZVwiOiBcImltcGxlbWVudGF0aW9uX2NvbXBsZXRpb25fcmVwb3J0XCIsXG4gICAgXCJyZWxheWxtX3N0YXR1c1wiOiBcImhpc3RvcmljYWxfYWZ0ZXJfbWVyZ2VcIixcbiAgICBcInJlbGF5bG1fdm9sYXRpbGl0eVwiOiBcImZyb3plblwiLFxufVxuTEVHQUNZX09OTFlfQU5DSE9SUyA9IChcbiAgICBcInJlbGF5bG1fZG9jX3R5cGU6IGltcGxlbWVudGF0aW9uX2NvbXBsZXRpb25fcmVwb3J0XCIsXG4gICAgXCJyZWxheWxtX3N0YXR1czogaGlzdG9yaWNhbF9hZnRlcl9tZXJnZVwiLFxuICAgIFwicmVsYXlsbV92b2xhdGlsaXR5OiBmcm96ZW5cIixcbiAgICBcIiMjIFN0YXR1cyBhbmQgYXV0aG9yaXR5XCIsXG4gICAgXCJyZWxheWxtX3NvdXJjZV9jb21taXQ6XCIsXG4gICAgXCJyZWxheWxtX3NvdXJjZV9ibG9iOlwiLFxuICAgIFwicmVsYXlsbV9zb3VyY2VfY29udGVudF9zaGEyNTY6XCIsXG4gICAgXCJyZWxheWxtX2V4YWN0X3NvdXJjZV9zbmFwc2hvdDpcIixcbilcblxuRVhJU1RJTkdfRVZJREVOQ0VfUFJPRklMRSA9IHtcbiAgICBcInJlbGF5bG1fZG9jX3R5cGVcIjogXCJldmlkZW5jZVwiLFxuICAgIFwicmVsYXlsbV9zdGF0dXNcIjogXCJmcm96ZW5cIixcbiAgICBcInJlbGF5bG1fdm9sYXRpbGl0eVwiOiBcImxvd1wiLFxufVxuRVhJU1RJTkdfRVZJREVOQ0VfQU5DSE9SUyA9IChcbiAgICBcInJlbGF5bG1fZG9jX3R5cGU6IGV2aWRlbmNlXCIsXG4gICAgXCJyZWxheWxtX3N0YXR1czogZnJvemVuXCIsXG4gICAgXCJyZWxheWxtX3ZvbGF0aWxpdHk6IGxvd1wiLFxuKVxuXG5cbmRlZiByZWFkX3RleHQocmVsYXRpdmVfcGF0aDogc3RyKSAtPiBzdHI6XG4gICAgcGF0aCA9IFJPT1QgLyByZWxhdGl2ZV9wYXRoXG4gICAgZGF0YSA9IHBhdGgucmVhZF9ieXRlcygpXG4gICAgaWYgbGVuKGRhdGEpID4gTUFYX0JZVEVTOlxuICAgICAgICByYWlzZSBBc3NlcnRpb25FcnJvcihmXCJ7cmVsYXRpdmVfcGF0aH06IGZpbGUgZXhjZWVkcyBzaXplIGJvdW5kXCIpXG4gICAgcmV0dXJuIGRhdGEuZGVjb2RlKFwidXRmLThcIilcblxuXG5kZWYgcmVxdWlyZV9hbmNob3JzKHJlbGF0aXZlX3BhdGg6IHN0ciwgYW5jaG9yczogdHVwbGVbc3RyLCAuLi5dKSAtPiBOb25lOlxuICAgIGJvZHkgPSByZWFkX3RleHQocmVsYXRpdmVfcGF0aClcbiAgICBtaXNzaW5nID0gW2FuY2hvciBmb3IgYW5jaG9yIGluIGFuY2hvcnMgaWYgYW5jaG9yIG5vdCBpbiBib2R5XVxuICAgIGlmIG1pc3Npbmc6XG4gICAgICAgIHJhaXNlIEFzc2VydGlvbkVycm9yKGYXCJ7cmVsYXRpdmVfcGF0aH06IG1pc3NpbmcgYW5jaG9yczoge21pc3Npbmchcn1cIilcblxuXG5kZWYgcGFyc2VfZmxhdF9mcm9udF9tYXR0ZXIocmVsYXRpdmVfcGF0aDogc3RyLCByYXc6IHN0cikgLT4gZGljdFtzdHIsIG9iamVjdF06XG4gICAgbWV0YWRhdGE6IGRpY3Rbc3RyLCBvYmplY3RdID0ge31cbiAgICBjdXJyZW50X2xpc3Rfa2V5OiBzdHIgfCBOb25lID0gTm9uZVxuICAgIGZvciBsaW5lIGluIHJhdy5zcGxpdGxpbmVzKCk6XG4gICAgICAgIGlmIG5vdCBsaW5lLnN0cmlwKCk6XG4gICAgICAgICAgICBjb250aW51ZVxuICAgICAgICBpZiBsaW5lLnN0YXJ0c3dpdGgoXCIgXCIpIGFuZCBsaW5lLnN0cmlwKCkuc3RhcnRzd2l0aChcIi0gXCIpOlxuICAgICAgICAgICAgaWYgY3VycmVudF9saXN0X2tleSBpcyBOb25lOlxuICAgICAgICAgICAgICAgIHJhaXNlIEFzc2VydGlvbkVycm9yKFxuICAgICAgICAgICAgICAgICAgICBmXCJ7cmVsYXRpdmVfcGF0aH06IGxpc3QgaXRlbSB3aXRoIG5vIHByZWNlZGluZyBrZXk6IHtsaW5lIXJ9XCJcbiAgICAgICAgICAgICAgICApXG4gICAgICAgICAgICB2YWx1ZSA9IG1ldGFkYXRhW2N1cnJlbnRfbGlzdF9rZXldXG4gICAgICAgICAgICBpZiBub3QgaXNpbnN0YW5jZSh2YWx1ZSwgbGlzdCk6XG4gICAgICAgICAgICAgICAgcmFpc2UgQXNzZXJ0aW9uRXJyb3IoXG4gICAgICAgICAgICAgICAgICAgIGZcIntyZWxhdGl2ZV9wYXRofTogbGlzdCBpdGVtIGZvbGxvd3Mgbm9uLWxpc3Qga2V5IHtjdXJyZW50X2xpc3Rfa2V5IXJ9XCJcbiAgICAgICAgICAgICAgICApXG4gICAgICAgICAgICB2YWx1ZS5hcHBlbmQobGluZS5zdHJpcCgpWzI6XS5zdHJpcCgpKVxuICAgICAgICAgICAgY29udGludWVcbiAgICAgICAgaWYgXCI6XCIgbm90IGluIGxpbmU6XG4gICAgICAgICAgICByYWlzZSBBc3NlcnRpb25FcnJvcihcbiAgICAgICAgICAgICAgICBmXCJ7cmVsYXRpdmVfcGF0aH06IHVucGFyc2VhYmxlIGZyb250IG1hdHRlciBsaW5lOiB7bGluZSFyfVwiXG4gICAgICAgICAgICApXG4gICAgICAgIGtleSwgXywgdmFsdWUgPSBsaW5lLnBhcnRpdGlvbihcIjpcIilcbiAgICAgICAga2V5ID0ga2V5LnN0cmlwKClcbiAgICAgICAgdmFsdWUgPSB2YWx1ZS5zdHJpcCgpXG4gICAgICAgIGlmIHZhbHVlOlxuICAgICAgICAgICAgbWV0YWRhdGFba2V5XSA9IHZhbHVlXG4gICAgICAgICAgICBjdXJyZW50X2xpc3Rfa2V5ID0gTm9uZVxuICAgICAgICBlbHNlOlxuICAgICAgICAgICAgbWV0YWRhdGFba2V5XSA9IFtdXG4gICAgICAgICAgICBjdXJyZW50X2xpc3Rfa2V5ID0ga2V5XG4gICAgcmV0dXJuIG1ldGFkYXRhXG5cblxuZGVmIHBhcnNlX2Zyb250X21hdHRlcihyZWxhdGl2ZV9wYXRoOiBzdHIpIC0+IHR1cGxlW2RpY3Rbc3RyLCBvYmplY3RdLCBzdHJdOlxuICAgIHRleHQgPSByZWFkX3RleHQocmVsYXRpdmVfcGF0aClcbiAgICBsaW5lcyA9IHRleHQuc3BsaXRsaW5lcygpXG4gICAgaWYgbm90IGxpbmVzIG9yIGxpbmVzWzBdLnN0cmlwKCkgIT0gXCItLS1cIjpcbiAgICAgICAgcmFpc2UgQXNzZXJ0aW9uRXJyb3IoZiXCJ7cmVsYXRpdmVfcGF0aH06IG1pc3NpbmcgWUFNTCBmcm9udCBtYXR0ZXJcIilcbiAgICB0cnk6XG4gICAgICAgIGVuZCA9IG5leHQoXG4gICAgICAgICAgICBpbmRleCBmb3IgaW5kZXgsIGxpbmUgaW4gZW51bWVyYXRlKGxpbmVzWzE6XSwgMSkgaWYgbGluZS5zdHJpcCgpID09IFwiLS0tXCJcbiAgICAgICAgKVxuICAgIGV4Y2VwdCBTdG9wSXRlcmF0aW9uIGFzIGV4YzpcbiAgICAgICAgcmFpc2UgQXNzZXJ0aW9uRXJyb3IoZiXCJ7cmVsYXRpdmVfcGF0aH06IHVudGVybWluYXRlZCBZQU1MIGZyb250IG1hdHRlclwiKSBmcm9tIGV4Y1xuICAgIG1ldGFkYXRhID0gcGFyc2VfZmxhdF9mcm9udF9tYXR0ZXIocmVsYXRpdmVfcGF0aCwgXCJcbi5qb2luKGxpbmVzWzE6ZW5kXSkpXG4gICAgcmV0dXJuIG1ldGFkYXRhLCBcIlxuXCIuam9pbihsaW5lc1tlbmQgKyAxIDpdKVxuXG5cbmRlZiBkZXRlcm1pbmVfcHJvZmlsZShyZWxhdGl2ZV9wYXRoOiBzdHIsIG1ldGFkYXRhOiBkaWN0W3N0ciwgb2JqZWN0XSkgLT4gc3RyOlxuICAgIGNhbmRpZGF0ZSA9IHtcbiAgICAgICAgXCJyZWxheWxtX2RvY190eXBlXCI6IG1ldGFkYXRhLmdldChcInJlbGF5bG1fZG9jX3R5cGVcIiksXG4gICAgICAgIFwicmVsYXlsbV9zdGF0dXNcIjogbWV0YWRhdGEuZ2V0KFwicmVsYXlsbV9zdGF0dXNcIiksXG4gICAgICAgIFwicmVsYXlsbV92b2xhdGlsaXR5XCI6IG1ldGFkYXRhLmdldChcInJlbGF5bG1fdm9sYXRpbGl0eVwiKSxcbiAgICB9XG4gICAgaWYgY2FuZGlkYXRlID09IExFR0FDWV9QUk9GSUxFOlxuICAgICAgICByZXR1cm4gXCJsZWdhY3lcIlxuICAgIGlmIGNhbmRpZGF0ZSA9PSBFWElTVElOR19FVklERU5DRV9QUk9GSUxFOlxuICAgICAgICByZXR1cm4gXCJleGlzdGluZ19ldmlkZW5jZVwiXG4gICAgcmFpc2UgQXNzZXJ0aW9uRXJyb3IoXG4gICAgICAgIGYXCJ7cmVsYXRpdmVfcGF0aH06IHVucmVjb2duaXplZCBvciBtaXhlZCBjb21wbGV0aW9uLXJlcG9ydCBwcm9maWxlIFwiXG4gICAgICAgIGZcIihkb2NfdHlwZT17Y2FuZGlkYXRlWydyZWxheWxtX2RvY190eXBlJ10hcn0sIFwiXG4gICAgICAgIGZcInN0YXR1cz17Y2FuZGlkYXRlWydyZWxheWxtX3N0YXR1cyddIXJ9LCBcIlxuICAgICAgICBmXCJ2b2xhdGlsaXR5PXtjYW5kaWRhdGVbJ3JlbGF5bG1fdm9sYXRpbGl0eSddIXJ9KVwiXG4gICAgKVxuXG5cbmRlZiB2YWxpZGF0ZV9yZXBvcnQocmVsYXRpdmVfcGF0aDogc3RyKSAtPiBOb25lOlxuICAgIHBhdGggPSBQYXRoKHJlbGF0aXZlX3BhdGgpXG4gICAgcGFydHMgPSBwYXRoLnBhcnRzXG4gICAgaWYgbGVuKHBhcnRzKSAhPSA0IG9yIHBhcnRzWzozXSAhPSBSRVBPUlRfRElSRUNUT1JZLnBhcnRzOlxuICAgICAgICByYWlzZSBBc3NlcnRpb25FcnJvcihcbiAgICAgICAgICAgIGZcIntyZWxhdGl2ZV9wYXRofTogcmVwb3J0IG11c3QgYmUgdW5kZXIgdHJhbnNpdGlvbmFsIFwiXG4gICAgICAgICAgICBmXCJ7UkVQT1JUX0RJUkVDVE9SWS5hc19wb3NpeCgpfS9cIlxuICAgICAgICApXG4gICAgaWYgbm90IHBhdGgubmFtZS5lbmRzd2l0aChcIl9jb21wbGV0aW9uX3JlcG9ydC5tZFwiKTpcbiAgICAgICAgcmFpc2UgQXNzZXJ0aW9uRXJyb3IoZiXCJ7cmVsYXRpdmVfcGF0aH06IGludmFsaWQgY29tcGxldGlvbiByZXBvcnQgZmlsZW5hbWVcIilcbiAgICBpZiBcIi4uXCIgaW4gcGFydHM6XG4gICAgICAgIHJhaXNlIEFzc2VydGlvbkVycm9yKGYXCJ7cmVsYXRpdmVfcGF0aH06IHBhcmVudCB0cmF2ZXJzYWwgaXMgbm90IGFsbG93ZWRcIilcblxuICAgIG1ldGFkYXRhLCBfID0gcGFyc2VfZnJvbnRfbWF0dGVyKHJlbGF0aXZlX3BhdGgpXG4gICAgcHJvZmlsZSA9IGRldGVybWluZV9wcm9maWxlKHJlbGF0aXZlX3BhdGgsIG1ldGFkYXRhKVxuICAgIHJlcXVpcmVfYW5jaG9ycyhyZWxhdGl2ZV9wYXRoLCBTSEFSRURfUkVQT1JUX0FOQ0hPUlMpXG4gICAgaWYgcHJvZmlsZSA9PSBcImxlZ2FjeVwiOlxuICAgICAgICByZXF1aXJlX2FuY2hvcnMocmVsYXRpdmVfcGF0aCwgTEVHQUNZX09OTFlfQU5DSE9SUylcbiAgICBlbHNlOlxuICAgICAgICByZXF1aXJlX2FuY2hvcnMocmVsYXRpdmVfcGF0aCwgRVhJU1RJTkdfRVZJREVOQ0VfQU5DSE9SUylcblxuICAgIGJvZHkgPSByZWFkX3RleHQocmVsYXRpdmVfcGF0aClcbiAgICBwcl9saW5lcyA9IFtsaW5lIGZvciBsaW5lIGluIGJvZHkuc3BsaXRsaW5lcygpIGlmIGxpbmUuc3RhcnRzd2l0aChcIi0gUFI6ICNcIildXG4gICAgaWYgbGVuKHByX2xpbmVzKSAhPSAxOlxuICAgICAgICByYWlzZSBBc3NlcnRpb25FcnJvcihmXCJ7cmVsYXRpdmVfcGF0aH06IG9uZSBzb3VyY2UgUFIgbGluZSByZXF1aXJlZFwiKVxuICAgIHByX3ZhbHVlID0gcHJfbGluZXNbMF0uc3BsaXQoXCIjXCIsIDEpWzFdLnN0cmlwKClcbiAgICBpZiBub3QgcHJfdmFsdWUuaXNkaWdpdCgpIG9yIHByX3ZhbHVlLnN0YXJ0c3dpdGgoXCIwXCIpOlxuICAgICAgICByYWlzZSBBc3NlcnRpb25FcnJvcihmXCJ7cmVsYXRpdmVfcGF0aH06IHNvdXJjZSBQUiBtdXN0IGJlIHBvc2l0aXZlIGRpZ2l0c1wiKVxuICAgIGlmIFwiLSBVUkw6IGh0dHBzOi8vZ2l0aHViLmNvbS9cIiBub3QgaW4gYm9keTpcbiAgICAgICAgcmFpc2UgQXNzZXJ0aW9uRXJyb3IoZiXCJ7cmVsYXRpdmVfcGF0aH06IGNvbmNyZXRlIHNvdXJjZSBQUiBVUkwgcmVxdWlyZWRcIilcbiAgICBmb3IgcGxhY2Vob2xkZXIgaW4gKFwiPHNsaWNlPlwiLCBcIjxudW1iZXI+XCIsIFwiVEJEXCIsIFwiVE8gQkUgRklMTEVEXCIpOlxuICAgICAgICBpZiBwbGFjZWhvbGRlciBpbiBib2R5OlxuICAgICAgICAgICAgcmFpc2UgQXNzZXJ0aW9uRXJyb3IoZiXCJ7cmVsYXRpdmVfcGF0aH06IHVucmVzb2x2ZWQgcGxhY2Vob2xkZXIge3BsYWNlaG9sZGVyIXJ9XCIpXG5cblxuZGVmIGFsbF9yZXBvcnRfcGF0aHMoKSAtPiB0dXBsZVtzdHIsIC4uLl06XG4gICAgcmVwb3J0cyA9IChST09UIC8gUkVQT1JUX0RJUkVDVE9SWSkuZ2xvYihcIipfY29tcGxldGlvbl9yZXBvcnQubWRcIilcbiAgICByZXR1cm4gdHVwbGUocGF0aC5yZWxhdGl2ZV90byhST09UKS5hc19wb3NpeCgpIGZvciBwYXRoIGluIHNvcnRlZChyZXBvcnRzKSlcblxuXG5fRVhJU1RJTkdfRVZJREVOQ0VfUkVQT1JUID0gXCJcIlwiLS0tXG5yZWxheWxtX2RvY190eXBlOiBldmlkZW5jZVxucmVsYXlsbV9hdXRob3JpdHk6IGV4YW1wbGVfc2xpY2VfaW1wbGVtZW50YXRpb25fZXZpZGVuY2VcbnJlbGF5bG1fc3RhdHVzOiBmcm96ZW5cbnJlbGF5bG1fdm9sYXRpbGl0eTogbG93XG5yZWxheWxtX293bmVyOiBpbXBsZW1lbnRhdGlvblxucmVsYXlsbV91cGRhdGVfdHJpZ2dlcjpcbiAgLSBtZXRhZGF0YSBvciBsaW5rIHJlcGFpciBvbmx5XG5yZWxheWxtX2N1cnJlbnRfc3RhdHVzX3NvdXJjZTogLi4vLi4vUFJPSkVDVF9TVEFUVVMubWRcbnJlbGF5bG1fbm90X2F1dGhvcml0YXRpdmVfZm9yOlxuICAtIHJlcG9zaXRvcnktd2lkZSBjdXJyZW50IGltcGxlbWVudGF0aW9uIHN0YXR1c1xucmVsYXlsbV9zb3VyY2VfcHI6IDk5OTk5OVxucmVsYXlsbV9yZWNvcmRlZF9vbjogMjAyNi0wNy0xNVxuLS0tXG4jIEV4YW1wbGUgU2xpY2UgQ29tcGxldGlvbiBSZXBvcnRcblxuIyMgU2NvcGVcblxuRXhhbXBsZSBzY29wZS5cblxuIyMgSW1wbGVtZW50ZWQgcHJvZHVjdGlvbiBib3VuZGFyeVxuXG5FeGFtcGxlIGJvdW5kYXJ5LlxuXG4jIyBQcmVzZXJ2ZWQgYXV0aG9yaXRpZXMgYW5kIG5vbi1nb2Fsc1xuXG5FeGFtcGxlIG5vbi1nb2Fscy5cblxuIyMgQ2hhbmdlZCBmaWxlc1xuXG5FeGFtcGxlIGNoYW5nZWQgZmlsZXMuXG5cbiMjIFZhbGlkYXRpb24gZXZpZGVuY2VcblxuRXhhbXBsZSB2YWxpZGF0aW9uIGV2aWRlbmNlLlxuXG4jIyBLbm93biBsaW1pdGF0aW9uc1xuXG5FeGFtcGxlIGtub3duIGxpbWl0YXRpb25zLlxuXG4jIyBTaGFyZWQgZG9jdW1lbnRhdGlvbiB1cGRhdGUgaW5wdXRzXG5cbkV4YW1wbGUgc2hhcmVkIGlucHV0cy5cblxuIyMgU291cmNlIHB1bGwgcmVxdWVzdFxuXG4tIFBSOiAjOTk5OTk5XG4tIFVSTDogaHR0cHM6Ly9naXRodWIuY29tL3JpbnNha2Ftby9yZWxheS1sbS9wdWxsLzk5OTk5OVxuXCJcIlwiXG5cbl9MRUdBQ1lfUkVQT1JUID0gXCJcIlwiLS0tXG5yZWxheWxtX2RvY190eXBlOiBpbXBsZW1lbnRhdGlvbl9jb21wbGV0aW9uX3JlcG9ydFxucmVsYXlsbV9hdXRob3JpdHk6IGV4YW1wbGVfc2xpY2VfZXZpZGVuY2VcbnJlbGF5bG1fc3RhdHVzOiBoaXN0b3JpY2FsX2FmdGVyX21lcmdlXG5yZWxheWxtX3ZvbGF0aWxpdHk6IGZyb3plblxucmVsYXlsbV9vd25lcjogaW1wbGVtZW50YXRpb25cbnJlbGF5bG1fdXBkYXRlX3RyaWdnZXI6XG4gIC0gbWV0YWRhdGEgb3IgbGluayByZXBhaXIgb25seVxucmVsYXlsbV9jdXJyZW50X3N0YXR1c19zb3VyY2U6IC4uLy4uL1BST0pFQ1RfU1RBVFVTLm1kXG5yZWxheWxtX25vdF9hdXRob3JpdGF0aXZlX2ZvcjpcbiAgLSByZXBvc2l0b3J5LXdpZGUgY3VycmVudCBpbXBsZW1lbnRhdGlvbiBzdGF0dXNcbnJlbGF5bG1fc291cmNlX2NvbW1pdDogMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwYVxucmVsYXlsbV9zb3VyY2Vfb3JpZ2luX2NvbW1pdDogMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwYVxucmVsYXlsbV9zb3VyY2VfcHI6IDk5OTk5OFxucmVsYXlsbV9yZWNvcmRlZF9vbjogMjAyNi0wNy0xNVxucmVsYXlsbV9zb3VyY2VfYmxvYjogMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwYlxucmVsYXlsbV9zb3VyY2VfY29udGVudF9zaGEyNTY6IDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwY1xucmVsYXlsbV9wcmVfY3V0b3Zlcl9ibG9iOiAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBiXG5yZWxheWxtX3ByZV9jdXRvdmVyX2NvbnRlbnRfc2hhMjU2OiAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwY1xucmVsYXlsbV9leGFjdF9zb3VyY2Vfc25hcHNob3Q6IGV4YW1wbGUtc291cmNlLnR4dFxuLS0tXG4jIEV4YW1wbGUgU2xpY2UgQ29tcGxldGlvbiBSZXBvcnRcblxuIyMgU3RhdHVzIGFuZCBhdXRob3JpdHlcblxuSGlzdG9yaWNhbCBib3VuZGFyeS5cblxuIyMgU2NvcGVcblxuRXhhbXBsZSBzY29wZS5cblxuIyMgSW1wbGVtZW50ZWQgcHJvZHVjdGlvbiBib3VuZGFyeVxuXG5FeGFtcGxlIGJvdW5kYXJ5LlxuXG4jIyBQcmVzZXJ2ZWQgYXV0aG9yaXRpZXMgYW5kIG5vbi1nb2Fsc1xuXG5FeGFtcGxlIG5vbi1nb2Fscy5cblxuIyMgQ2hhbmdlZCBmaWxlc1xuXG5FeGFtcGxlIGNoYW5nZWQgZmlsZXMuXG5cbiMjIFZhbGlkYXRpb24gZXZpZGVuY2VcblxuRXhhbXBsZSB2YWxpZGF0aW9uIGV2aWRlbmNlLlxuXG4jIyBLbm93biBsaW1pdGF0aW9uc1xuXG5FeGFtcGxlIGtub3duIGxpbWl0YXRpb25zLlxuXG4jIyBTaGFyZWQgZG9jdW1lbnRhdGlvbiB1cGRhdGUgaW5wdXRzXG5cbkV4YW1wbGUgc2hhcmVkIGlucHV0cy5cblxuIyMgU291cmNlIHB1bGwgcmVxdWVzdFxuXG4tIFBSOiAjOTk5OTk4XG4tIFVSTDogaHR0cHM6Ly9naXRodWIuY29tL3JpbnNha2Ftby9yZWxheS1sbS9wdWxsLzk5OTk5OFxuXCJcIlwiXG5cblxuZGVmIHdyaXRlX3JlcG9ydChiYXNlOiBQYXRoLCBuYW1lOiBzdHIsIHRleHQ6IHN0cikgLT4gc3RyOlxuICAgIHRhcmdldF9kaXIgPSBiYXNlIC8gUkVQT1JUX0RJUkVDVE9SWG4gICAgdGFyZ2V0X2Rpci5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpXG4gICAgdGFyZ2V0ID0gdGFyZ2V0X2RpciAvIG5hbWVcbiAgICB0YXJnZXQud3JpdGVfdGV4dCh0ZXh0LCBlbmNvZGluZz1cInV0Zi04XCIpXG4gICAgcmV0dXJuIHRhcmdldC5yZWxhdGl2ZV90byhiYXNlKS5hc19wb3NpeCgpXG5cblxuZGVmIHNlbGZfdGVzdCgpIC0+IE5vbmU6XG4gICAgZ2xvYmFsIFJPT1RcbiAgICByZWFsX3Jvb3QgPSBST09UXG4gICAgcmVzdWx0czogbGlzdFt0dXBsZVtzdHIsIGJvb2wsIHN0cl1dID0gW11cblxuICAgIGRlZiBjaGVjayhuYW1lOiBzdHIsIGZuOiBDYWxsYWJsZVtbXSwgTm9uZV0pIC0+IE5vbmU6XG4gICAgICAgIHRyeTpcbiAgICAgICAgICAgIGZuKClcbiAgICAgICAgICAgIHJlc3VsdHMuYXBwZW5kKChuYW1lLCBUcnVlLCBcIlwiKSlcbiAgICAgICAgZXhjZXB0IEFzc2VydGlvbkVycm9yIGFzIGV4YzpcbiAgICAgICAgICAgIHJlc3VsdHMuYXBwZW5kKChuYW1lLCBGYWxzZSwgc3RyKGV4YykpKVxuXG4gICAgZGVmIGNoZWNrX3JlamVjdHMobmFtZTogc3RyLCBmbjogQ2FsbGFibGVbW10sIE5vbmVdLCBleHBlY3RlZDogc3RyKSAtPiBOb25lOlxuICAgICAgICB0cnk6XG4gICAgICAgICAgICBmbigpXG4gICAgICAgICAgICByZXN1bHRzLmFwcGVuZCgobmFtZSwgRmFsc2UsIFwiZXhwZWN0ZWQgQXNzZXJ0aW9uRXJyb3IsIG5vbmUgcmFpc2VkXCIpKVxuICAgICAgICBleGNlcHQgQXNzZXJ0aW9uRXJyb3IgYXMgZXhjOlxuICAgICAgICAgICAgbWVzc2FnZSA9IHN0cihleGNpKVxuICAgICAgICAgICAgcmVzdWx0cy5hcHBlbmQoKG5hbWUsIGV4cGVjdGVkIGluIG1lc3NhZ2UsIFwiXCIgaWYgZXhwZWN0ZWQgaW4gbWVzc2FnZSBlbHNlIG1lc3NhZ2UpKVxuXG4gICAgZGVmIHJlYWxfcmVwb3J0c19wYXNzKCkgLT4gTm9uZTpcbiAgICAgICAgcGF0aHMgPSBhbGxfcmVwb3J0X3BhdGhzKClcbiAgICAgICAgaWYgbm90IHBhdGhzOlxuICAgICAgICAgICAgcmFpc2UgQXNzZXJ0aW9uRXJyb3IoXCJyZWFsIHJlcG9zaXRvcnkgaGFzIG5vIHRyYW5zaXRpb25hbCBjb21wbGV0aW9uIHJlcG9ydHNcIilcbiAgICAgICAgZm9yIHJlcG9ydF9wYXRoIGluIHBhdGhzOlxuICAgICAgICAgICAgdmFsaWRhdGVfcmVwb3J0KHJlcG9ydF9wYXRoKVxuXG4gICAgY2hlY2soXCJyZWFsIHJlcG9zaXRvcnkgdHJhbnNpdGlvbmFsIGNvbXBsZXRpb24gcmVwb3J0cyBwYXNzXCIsIHJlYWxfcmVwb3J0c19wYXNzKVxuXG4gICAgd2l0aCB0ZW1wZmlsZS5UZW1wb3JhcnlEaXJlY3RvcnkoKSBhcyB0ZDpcbiAgICAgICAgUk9PVCA9IFBhdGgodGQpXG4gICAgICAgIHJlbCA9IHdyaXRlX3JlcG9ydChST09ULCBcImV4YW1wbGVfY29tcGxldGlvbl9yZXBvcnQubWRcIiwgX0VYSVNUSU5HX0VWSURFTkNFX1JFUE9SVCpcbiAgICAgICAgY2hlY2soXCJleGlzdGluZyBldmlkZW5jZS9mcm96ZW4vbG93IHJlcG9ydCBwYXNzZXNcIiwgbGFtYmRhOiB2YWxpZGF0ZV9yZXBvcnQocmVsKSlcbiAgICBST09UID0gcmVhbF9yb290XG5cbiAgICB3aXRoIHRlbXBmaWxlLlRlbXBvcmFyeURpcmVjdG9yeSgpIGFzIHRkOlxuICAgICAgICBST09UID0gUGF0aCh0ZClcbiAgICAgICAgcmVsID0gd3JpdGVfcmVwb3J0KFJPT1QsIFwiZXhhbXBsZV9jb21wbGV0aW9uX3JlcG9ydC5tZFwiLCBfTEVHQUNZX1JFUE9SVCpcbiAgICAgICAgY2hlY2soXG4gICAgICAgICAgICBcImxlZ2FjeSBpbXBsZW1lbnRhdGlvbl9jb21wbGV0aW9uX3JlcG9ydCBwcm9maWxlIHBhc3Nlc1wiLFxuICAgICAgICAgICAgbGFtYmRhOiB2YWxpZGF0ZV9yZXBvcnQocmVsKSxcbiAgICAgICAgKVxuICAgIFJPT1QgPSByZWFsX3Jvb3RcblxuXG4gICAgd2l0aCB0ZW1wZmlsZS5UZW1wb3JhcnlEaXJlY3RvcnkoKSBhcyB0ZDpcbiAgICAgICAgUk9PVCA9IFBhdGgodGQpXG4gICAgICAgIG1peGVkID0gX0VYSVNUSU5HX0VWSURFTkNFX1JFUE9SVC5yZXBsYWNlKFxuICAgICAgICAgICAgXCJyZWxheWxtX3N0YXR1czogZnJvemVuXCIsIFwicmVsYXlsbV9zdGF0dXM6IGhpc3RvcmljYWxfYWZ0ZXJfbWVyZ2VcIiwgMVxuICAgICAgICApXG4gICAgICAgIHJlbCA9IHdyaXRlX3JlcG9ydChST09ULCBcImV4YW1wbGVfY29tcGxldGlvbl9yZXBvcnQubWRcIiwgbWl4ZWQpXG4gICAgICAgIGNoZWNrX3JlamVjdHMoXG4gICAgICAgICAgICBcIm1peGVkIHByb2ZpbGUgaXMgcmVqZWN0ZWRcIixcbiAgICAgICAgICAgIGxhbWJkYTogdmFsaWRhdGVfcmVwb3J0KHJlbCksXG4gICAgICAgICAgICBcInVucmVjb2duaXplZCBvciBtaXhlZCBjb21wbGV0aW9uLXJlcG9ydCBwcm9maWxlXCIsXG4gICAgICAgIClcbiAgICBST09UID0gcmVhbF9yb290XG5cbiAgICB3aXRoIHRlbXBmaWxlLlRlbXBvcmFyeURpcmVjdG9yeSgpIGFzIHRkOlxuICAgICAgICBST09UID0gUGF0aCh0ZClcbiAgICAgICAgdW5yZXNvbHZlZCA9IF9FWElTVElOR19FVklERU5DRV9SRVBPUlQucmVwbGFjZShcbiAgICAgICAgICAgIFwiRXhhbXBsZSBrbm93biBsaW1pdGF0aW9ucy5cIiwgXCJUQkRcIiwgMVxuICAgICAgICApXG4gICAgICAgIHJlbCA9IHdyaXRlX3JlcG9ydChST09ULCBcImV4YW1wbGVfY29tcGxldGlvbl9yZXBvcnQubWRcIiwgdW5yZXNvbHZlZClcbiAgICAgICAgY2hlY2tfcmVqZWN0cyhcbiAgICAgICAgICAgIFwidW5yZXNvbHZlZCBwbGFjZWhvbGRlciBpcyByZWplY3RlZFwiLFxuICAgICAgICAgICAgbGFtYmRhOiB2YWxpZGF0ZV9yZXBvcnQocmVsKSxcbiAgICAgICAgICAgIFwidW5yZXNvbHZlZCBwbGFjZWhvbGRlclwiLFxuICAgICAgICApXG4gICAgUk9PVCA9IHJlYWxfcm9vdFxuXG4gICAgd2l0aCB0ZW1wZmlsZS5UZW1wb3JhcnlEaXJlY3RvcnkoKSBhcyB0ZDpcbiAgICAgICAgUk9PVCA9IFBhdGgodGQpXG4gICAgICAgIG91dHNpZGUgPSBST09UIC8gXCJkb2NzXCIgLyBcIm90aGVyXCIgLyBcImV4YW1wbGVfY29tcGxldGlvbl9yZXBvcnQubWRcIlxuICAgICAgICBvdXRzaWRlLnBhcmVudC5ta2RpcihwYXJlbnRzPVRydWUpXG4gICAgICAgIG91dHNpZGUud3JpdGVfdGV4dChfRVhJU1RJTkdfRVZJREVOQ0VfUkVQT1JULCBlbmNvZGluZz1cInV0Zi04XCIpXG4gICAgICAgIGNoZWNrX3JlamVjdHMoXG4gICAgICAgICAgICBcInJlcG9ydCBvdXRzaWRlIHRyYW5zaXRpb25hbCBkaXJlY3RvcnkgaXMgcmVqZWN0ZWRcIixcbiAgICAgICAgICAgIGxhbWJkYTogdmFsaWRhdGVfcmVwb3J0KFwiZG9jcy9vdGhlci9leGFtcGxlX2NvbXBsZXRpb25fcmVwb3J0Lm1kXCIpLFxuICAgICAgICAgICAgXCJtdXN0IGJlIHVuZGVyIHRyYW5zaXRpb25hbFwiLFxuICAgICAgICApXG4gICAgUk9PVCA9IHJlYWxfcm9vdFxuXG4gICAgZmFpbGVkID0gWyhuYW1lLCBtZXNzYWdlKSBmb3IgbmFtZSwgb2ssIG1lc3NhZ2UgaW4gcmVzdWx0cyBpZiBub3Qgb2tdXG4gICAgZm9yIG5hbWUsIG9rLCBtZXNzYWdlIGluIHJlc3VsdHM6XG4gICAgICAgIHN0YXR1cyA9IFwiUEFTU1wiIGlmIG9rIGVsc2UgXCJGQUlMXCJcbiAgICAgICAgc3VmZml4ID0gZlwiICh7bWVzc2FnZX0pXCIgaWYgbWVzc2FnZSBhbmQgbm90IG9rIGVsc2UgXCJcIlxuICAgICAgICBwcmludChmXCJ7c3RhdHVzfToge25hbWV9e3N1ZmZpeH1cIilcbiAgICBpZiBmYWlsZWQ6XG4gICAgICAgIHByaW50KFxuICAgICAgICAgICAgZlwiXFxuU0VMRi1URVNUIEZBSUxFRDoge2xlbihmYWlsZWQpfS97bGVuKHJlc3VsdHMpfSBhc3NlcnRpb25zIGZhaWxlZFwiLFxuICAgICAgICAgICAgZmlsZT1zeXMuc3RkZXJyLFxuICAgICAgICApXG4gICAgICAgIHJhaXNlIFN5c3RlbUV4aXQoMSlcbiAgICBwcmludChmXCJcXG5SZWxheUxNIHRyYW5zaXRpb25hbCBjb21wbGV0aW9uLXJlcG9ydCB2YWxpZGF0b3Igc2VsZi10ZXN0IHBhc3NlZDoge2xlbihyZXN1bHRzKX0gYXNzZXJ0aW9uc1wiKVxuXG5cbmRlZiBtYWluKCkgLT4gTm9uZTpcbiAgICBwYXJzZXIgPSBhcmdwYXJzZS5Bcmd1bWVudFBhcnNlcigpXG4gICAgcGFyc2VyLmFkZF9hcmd1bWVudChcInBhdGhzXCIsIG5hcmdzPVwiKlwiKVxuICAgIHBhcnNlci5hZGRfYXJndW1lbnQoXCItLWNoZWNrLWFsbFwiLCBhY3Rpb249XCJzdG9yZV90cnVlXCIpXG4gICAgcGFyc2VyLmFkZF9hcmd1bWVudChcIi0tc2VsZi10ZXN0XCIsIGFjdGlvbj1cInN0b3JlX3RydWVcIilcbiAgICBhcmdzID0gcGFyc2VyLnBhcnNlX2FyZ3MoKVxuXG4gICAgaWYgYXJncy5zZWxmX3Rlc3Q6XG4gICAgICAgIHNlbGZfdGVzdCgpXG4gICAgICAgIHJldHVyblxuICAgIGlmIG5vdCBhcmdzLmNoZWNrX2FsbCBhbmQgbm90IGFyZ3MucGF0aHM6XG4gICAgICAgIGFyZ3MuY2hlY2tfYWxsID0gVHJ1ZVxuXG4gICAgcGF0aHMgPSBsaXN0KGFyZ3MucGF0aHMpXG4gICAgaWYgYXJncy5jaGVja19hbGw6XG4gICAgICAgIHBhdGhzLmV4dGVuZChhbGxfcmVwb3J0X3BhdGhzKCkpXG4gICAgZm9yIHJlbGF0aXZlX3BhdGggaW4gZGljdC5mcm9ta2V5cyhwYXRocyk6XG4gICAgICAgIHZhbGlkYXRlX3JlcG9ydChyZWxhdGl2ZV9wYXRoKVxuICAgIHByaW50KFwiUmVsYXlMTSB0cmFuc2l0aW9uYWwgY29tcGxldGlvbi1yZXBvcnQgdmFsaWRhdGlvbiBwYXNzZWRcIilcblxuXG5pZiBfX25hbWVfXyA9PSBcIl9fbWFpbl9fXCI6XG4gICAgbWFpbigpXG4iLCAiZG9jc19yZWFkbWVfb2xkIjogIiMjIFBhcmFsbGVsIGltcGxlbWVudGF0aW9uIGRvY3VtZW50YXRpb24gcnVsZVxuXG5JbXBsZW1lbnRhdGlvbiBQUnMgYWRkIG9yIHVwZGF0ZSB0aGVpciBvd24gc2xpY2UgaGFuZG9mZiBhbmQgYGRvY3MvZXZpZGVuY2UvaW1wbGVtZW50YXRpb24vPHNsaWNlPl9jb21wbGV0aW9uX3JlcG9ydC5tZGAgb25seS4gU2hhcmVkIGN1cnJlbnQtc3RhdHVzIGFuZCBleGVjdXRpb24tcGxhbiBkb2N1bWVudHMgbWF5IHJlY2VpdmUgdGhlIG1pbmltdW0gYW5jaG9ycyBuZWVkZWQgdG8ga2VlcCBhY3RpdmUgdmFsaWRhdGlvbiBncmVlbiwgYnV0IHRoZSB3YXZlIGNvbnZlcmdlbmNlIFBSIHJlbWFpbnMgcmVzcG9uc2libGUgZm9yIHJlcG9zaXRvcnktd2lkZSBzeW50aGVzaXMuIFRoZSBuZXh0IHdhdmUgYW5kIHJlbGVhc2UvZXZhbHVhdGlvbiBnYXRlIHJlbWFpbiBjbG9zZWQgdW50aWwgdGhlIGNvbnZlcmdlbmNlIFBSIGxpbmtzIHRoZSBtZXJnZWQgcmVwb3J0cyBhbmQgdXBkYXRlcyBzaGFyZWQgY3VycmVudC1zdGF0dXMgZG9jdW1lbnRzLlxuIiwgImRvY3NfcmVhZG1lX25ldyI6ICIjIyBJbXBsZW1lbnRhdGlvbiBhbmQgY29udmVyZ2VuY2UgZXZpZGVuY2UgcnVsZVxuXG5JbXBsZW1lbnRhdGlvbiBQUnMgcmVjb3JkIGV4YWN0IHZhbGlkYXRpb24gZXZpZGVuY2UgaW4gdGhlaXIgcHVsbC1yZXF1ZXN0IGJvZHksIGRpcmVjdGx5IGNvdXBsZWQgdGVzdHMsIGFuZCBhbnkgY29udHJhY3QgY2hhbmdlIHRoYXQgbXVzdCBzaGlwIGF0b21pY2FsbHkuIFRoZXkgZG8gbm90IGNyZWF0ZSBhIHBlcm1hbmVudCBjb21wbGV0aW9uIHJlcG9ydCBvciBoYW5kb2ZmIGJ5IGRlZmF1bHQuIEEgY29tbWl0dGVkIG1hY2hpbmUgcmVjb3JkIGlzIGFsbG93ZWQgb25seSB3aGVuIGl0IHNhdGlzZmllcyBhbiBhbGxvd2xpc3RlZCByZXRhaW5lZC1yZWNvcmQgY2xhc3Mgd2l0aCBhIGNvbnRpbnVpbmcgY29uc3VtZXIuXG5cbkNvbnZlcmdlbmNlIHdvcmsgcmVhZHMgbWVyZ2VkIHB1bGwgcmVxdWVzdHMgYW5kIGV4YWN0LWhlYWQgdmFsaWRhdGlvbiwgdGhlbiB1cGRhdGVzIHNoYXJlZCBzdGF0dXMgb3Igc2VxdWVuY2luZyB0aHJvdWdoIHRoZSBvd25pbmcgYXV0aG9yaXR5LiBFeGlzdGluZyBjb21wbGV0aW9uIHJlcG9ydHMgcmVtYWluIHRyYW5zaXRpb25hbCBoaXN0b3JpY2FsIGlucHV0cyBkdXJpbmcgRDItRDY7IHRoZXkgZG8gbm90IGRlZmluZSB0aGUgY3VycmVudCBldmlkZW5jZS1jcmVhdGlvbiBtb2RlbCBvciBvcGVuIHRoZSBuZXh0IHdhdmUsIHJlbGVhc2UsIG9yIGV2YWx1YXRpb24gZ2F0ZS5cbiIsICJldmlkZW5jZV9zZWN0aW9uX25ldyI6ICIjIyBUcmFuc2l0aW9uYWwgY29tcGxldGlvbiByZXBvcnRzXG5cblRoaXMgY29sbGVjdGlvbiBpcyBhbiBleGlzdGluZy1vbmx5IGNvbXBhdGliaWxpdHkgc3VyZmFjZSBkdXJpbmcgRDItRDYuIERvIG5vdCBjcmVhdGUgYSBuZXcgY29tbWl0dGVkIGNvbXBsZXRpb24gcmVwb3J0IG9yIGhhbmRvZmYgYnkgZGVmYXVsdC4gSW1wbGVtZW50YXRpb24gZXZpZGVuY2UgYmVsb25ncyBpbiB0aGUgc291cmNlIHB1bGwgcmVxdWVzdCwgZGlyZWN0bHkgY291cGxlZCB0ZXN0cywgZXhhY3QgY29udHJhY3RzLCBhbmQgY3VycmVudCB2YWxpZGF0b3JzIHVubGVzcyBhIG1hY2hpbmUtcmVhZGFibGUgcmVjb3JkIHF1YWxpZmllcyBmb3IgYW4gYWxsb3dsaXN0ZWQgcmV0YWluZWQtcmVjb3JkIGNsYXNzLlxuXG5FeGlzdGluZyBgKl9jb21wbGV0aW9uX3JlcG9ydC5tZGAgZmlsZXMgbWF5IHJlY2VpdmUgb25seSBib3VuZGVkIG1ldGFkYXRhIG9yIGxpbmsgcmVwYWlyIGFuZCB0aGVpciByZXZpZXdlZCBzeW50aGVzaXMsIHJlY29yZCBjbGFzc2lmaWNhdGlvbiwgb3IgR2l0LXJldGlyZW1lbnQgZGlzcG9zaXRpb24uIFRoZSB0cmFuc2l0aW9uYWwgdmFsaWRhdG9yIGNoZWNrcyB0aGVpciBoaXN0b3JpY2FsIHByb2ZpbGUsIHJlcXVpcmVkIHNlY3Rpb25zLCBjb25jcmV0ZSBzb3VyY2UgcHVsbCByZXF1ZXN0LCBhbmQgdW5yZXNvbHZlZCBwbGFjZWhvbGRlcnM7IGl0IG93bnMgbm8gZG9jdW1lbnRhdGlvbi1tb2RlbCwgY3VycmVudC1zdGF0dXMsIGFyY2hpdGVjdHVyZSwgY29udHJhY3QsIG9yIGV2aWRlbmNlLWNyZWF0aW9uIGF1dGhvcml0eS5cbiIsICJtb2RlbF9vbGQiOiAiQSBuZXcgcGVybWFuZW50IGNvbXBsZXRpb24gcmVwb3J0IG9yIGhhbmRvZmYgaXMgbm90IGNyZWF0ZWQgYnkgZGVmYXVsdC4gQSByZXN1bHQgcmVtYWlucyBpbiBHaXQgYW5kIHB1bGwtcmVxdWVzdCBoaXN0b3J5IHVubGVzcyBpdCBxdWFsaWZpZXMgZm9yIGFuIGFsbG93bGlzdGVkIHJldGFpbmVkLXJlY29yZCBjbGFzcyB3aXRoIGEgY29udGludWluZyByZWxlYXNlLCBtaWdyYXRpb24sIGF1ZGl0LCByZWNvdmVyeSwgcm9sbGJhY2ssIHJldGlyZW1lbnQsIENJLCBvciBvcGVyYXRpb25hbCBjb25zdW1lci5cblxuQSBjb252ZXJnZW5jZSBQUiByZWFkcyBtZXJnZWQgaW1wbGVtZW50YXRpb24gZXZpZGVuY2UsIHZlcmlmaWVzIGNyb3NzLXNsaWNlIGJvdW5kYXJpZXMsIGFuZCB1cGRhdGVzIHNoYXJlZCBjdXJyZW50LXN0YXRlIGRvY3VtZW50cyBvbmx5IGFmdGVyIGV4YWN0LWhlYWQgdmFsaWRhdGlvbi4gUGxhbm5pbmctb25seSB3b3JrIGRvZXMgbm90IGNoYW5nZSBpbXBsZW1lbnRhdGlvbiBzdGF0dXMuXG4iLCAibW9kZWxfbmV3IjogIkEgbmV3IHBlcm1hbmVudCBjb21wbGV0aW9uIHJlcG9ydCBvciBoYW5kb2ZmIGlzIG5vdCBjcmVhdGVkIGJ5IGRlZmF1bHQuIEEgcmVzdWx0IHJlbWFpbnMgaW4gR2l0IGFuZCBwdWxsLXJlcXVlc3QgaGlzdG9yeSB1bmxlc3MgaXQgcXVhbGlmaWVzIGZvciBhbiBhbGxvd2xpc3RlZCByZXRhaW5lZC1yZWNvcmQgY2xhc3Mgd2l0aCBhIGNvbnRpbnVpbmcgcmVsZWFzZSwgbWlncmF0aW9uLCBhdWRpdCwgcmVjb3ZlcnksIHJvbGxiYWNrLCByZXRpcmVtZW50LCBDSSwgb3Igb3BlcmF0aW9uYWwgY29uc3VtZXIuXG5cblRoZSBmb3JtZXIgcmV1c2FibGUgaW1wbGVtZW50YXRpb24tY29tcGxldGlvbi1yZXBvcnQgdGVtcGxhdGUgYW5kIGl0cyBwcm9zZS1hbmNob3IgbW9kZWwgZ3VhcmQgYXJlIHJldGlyZWQuIEV4aXN0aW5nIGNvbXBsZXRpb24gcmVwb3J0cyByZW1haW4gYW4gZXhwbGljaXRseSBjbG9zZWQgdHJhbnNpdGlvbmFsIGZhbWlseSBhbmQgbWF5IGJlIHN0cnVjdHVyYWxseSB2YWxpZGF0ZWQgb25seSB1bnRpbCBEMi1ENiBhc3NpZ25zIHRoZWlyIGZpbmFsIGRpc3Bvc2l0aW9uLlxuXG5BIGNvbnZlcmdlbmNlIFBSIHJlYWRzIG1lcmdlZCBpbXBsZW1lbnRhdGlvbiBldmlkZW5jZSwgdmVyaWZpZXMgY3Jvc3Mtc2xpY2UgYm91bmRhcmllcywgYW5kIHVwZGF0ZXMgc2hhcmVkIGN1cnJlbnQtc3RhdGUgZG9jdW1lbnRzIG9ubHkgYWZ0ZXIgZXhhY3QtaGVhZCB2YWxpZGF0aW9uLiBQbGFubmluZy1vbmx5IHdvcmsgZG9lcyBub3QgY2hhbmdlIGltcGxlbWVudGF0aW9uIHN0YXR1cy5cbiIsICJjb250cmFjdF9tYXJrZXIiOiAiVW50aWwgdGhlbiB0aGUgYXNzZXRzIG1heSByZW1haW4sIGJ1dCBjbG9zZWQgZmFtaWxpZXMgY2Fubm90IGdyb3cuIEQ2IG93bnMgdGhlaXIgZmluYWwgcmV0aXJlbWVudC5cblxuIyMgRG9tYWluIHN5bnRoZXNpcyBvcmRlciBhbmQgYXV0aG9yaXR5IGdhdGVzXG4iLCAiY29udHJhY3RfcmVwbGFjZW1lbnQiOiAiVW50aWwgdGhlbiB0aGUgYXNzZXRzIG1heSByZW1haW4sIGJ1dCBjbG9zZWQgZmFtaWxpZXMgY2Fubm90IGdyb3cuIEQ2IG93bnMgdGhlaXIgZmluYWwgcmV0aXJlbWVudC5cblxuIyMjIENvbXBsZXRpb24tcmVwb3J0IGNvbXBhdGliaWxpdHlcblxuVGhlIGZvcm1lciByZXVzYWJsZSBjb21wbGV0aW9uLXJlcG9ydCB0ZW1wbGF0ZSwgaXRzIGAtLWNoZWNrLW1vZGVsYCBwcm9zZS1hbmNob3IgbW9kZSwgYW5kIHRoZSBkZWRpY2F0ZWQgbW9kZWwgd29ya2Zsb3cgYXJlIHJldGlyZWQgYnkgRDEuIEV4aXN0aW5nIGNvbXBsZXRpb24gcmVwb3J0cyByZW1haW4gb25seSBhcyBhIGNsb3NlZCB0cmFuc2l0aW9uYWwgc291cmNlIGZhbWlseS4gVGhlaXIgdmFsaWRhdG9yIG1heSBjaGVjayB0aGUgYWxyZWFkeS1jb21taXR0ZWQgZmlsZSBwcm9maWxlLCByZXF1aXJlZCBzZWN0aW9ucywgY29uY3JldGUgc291cmNlIHB1bGwgcmVxdWVzdCwgYW5kIHVucmVzb2x2ZWQgcGxhY2Vob2xkZXJzOyBpdCBtdXN0IG5vdCBkZWZpbmUgdGhlIGRvY3VtZW50YXRpb24gbW9kZWwsIGF1dGhvcml6ZSBuZXcgcmVwb3J0cywgb3IgcmVjcmVhdGUgdGhlIHRlbXBsYXRlLiBHaXQgcGx1cyB0aGUgcmV0aXJlbWVudCBtYW5pZmVzdCBpcyB0aGUgcmVjb3Zlcnkgc3VyZmFjZSBmb3IgdGhlIHJlbW92ZWQgdGVtcGxhdGUuXG5cbiMjIERvbWFpbiBzeW50aGVzaXMgb3JkZXIgYW5kIGF1dGhvcml0eSBnYXRlc1xuIiwgImF1ZGl0X3JlYWRtZV9ibG9jayI6ICIgICAgXCJkb2NzL2V2aWRlbmNlL2ltcGxlbWVudGF0aW9uL1JFQURNRS5tZFwiOiAoXG4gICAgICAgIFwibm8gYGRvY3MvbXZwL3dhdmUqL2AgcGF0aCBleGlzdHMgdG8gcm91dGUgdGhyb3VnaFwiLFxuICAgICksXG4ifQ==").decode("utf-8"))


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write(path: str, content: str) -> None:
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one occurrence, found {count}")
    return text.replace(old, new, 1)


write("scripts/relaylm_mvp_completion_report_smoke.py", PAYLOAD["completion_script"])

for relative in (
    ".github/workflows/documentation-completion-report-model.yml",
    ".github/workflows/d1-completion-guard-probe.yml",
):
    target = ROOT / relative
    if target.exists():
        target.unlink()

files_workflow = read(".github/workflows/documentation-completion-report-files.yml")
files_workflow = files_workflow.replace(
    "name: Documentation completion report files",
    "name: Transitional completion report files",
    1,
)
if "--self-test" not in files_workflow:
    files_workflow = files_workflow.rstrip() + (
        "\n      - run: python scripts/relaylm_mvp_completion_report_smoke.py --self-test\n"
    )
write(".github/workflows/documentation-completion-report-files.yml", files_workflow)

wave4 = read(".github/workflows/wave4-cross-slice-convergence.yml")
wave4 = wave4.replace(
    "python scripts/relaylm_mvp_completion_report_smoke.py --check-model --check-all",
    "python scripts/relaylm_mvp_completion_report_smoke.py --check-all",
)
if "--check-model" in wave4:
    raise SystemExit("wave4 still invokes --check-model")
write(".github/workflows/wave4-cross-slice-convergence.yml", wave4)

registry = read("scripts/relaylm_mvp_eval_runner_registry.py")
registry = registry.replace(
    '("--check-model", "docs/evidence/implementation/mvp_eval_runner_completion_report.md"),',
    '("docs/evidence/implementation/mvp_eval_runner_completion_report.md",),',
)
if "--check-model" in registry:
    raise SystemExit("MVP eval registry still invokes --check-model")
write("scripts/relaylm_mvp_eval_runner_registry.py", registry)

docs_readme = read("docs/README.md")
docs_readme = docs_readme.replace(
    "[Implementation evidence](evidence/implementation/README.md) — per-PR implementation completion reports and focused historical MVP evidence.",
    "[Implementation evidence](evidence/implementation/README.md) — transitional completion reports and focused historical MVP evidence awaiting D2-D6 disposition.",
)
docs_readme = replace_once(
    docs_readme,
    PAYLOAD["docs_readme_old"],
    PAYLOAD["docs_readme_new"],
    "docs README evidence rule",
)
write("docs/README.md", docs_readme)

evidence_readme = read("docs/evidence/implementation/README.md")
evidence_readme = evidence_readme.replace(
    "  - an implementation evidence record is added, moved, or retired",
    "  - a transitional completion report is repaired, dispositioned, or retired",
    1,
)
evidence_readme = evidence_readme.replace(
    "relaylm_status: current",
    "relaylm_status: compatibility",
    1,
)
start = evidence_readme.find("## Creating a new completion report")
end = evidence_readme.find("\n## Early MVP smoke records", start)
if start < 0 or end < 0:
    raise SystemExit("implementation evidence creation section not found")
evidence_readme = (
    evidence_readme[:start]
    + PAYLOAD["evidence_section_new"]
    + evidence_readme[end:]
)
write("docs/evidence/implementation/README.md", evidence_readme)

templates_readme = read("docs/templates/README.md")
template_line = "- [Implementation completion report](implementation-completion-report.md)\n"
if template_line not in templates_readme:
    raise SystemExit("templates index completion-report link missing")
write("docs/templates/README.md", templates_readme.replace(template_line, "", 1))

template = ROOT / "docs/templates/implementation-completion-report.md"
if not template.exists():
    raise SystemExit("completion-report template is already absent before D1 retirement")
template.unlink()

audit = read("scripts/relaylm_docs_semantic_audit.py")
audit = audit.replace(
    'RETIRED_TEMPLATE_PATHS = ("docs/mvp/IMPLEMENTATION_COMPLETION_REPORT_TEMPLATE.md",)\n',
    "",
)
audit = audit.replace(
    'CANONICAL_COMPLETION_REPORT_TEMPLATE_PATH = "docs/templates/implementation-completion-report.md"\n',
    "",
)
function_start = audit.find("def check_completion_report_template(errors: list[str]) -> None:")
function_end = audit.find("\nMVP_REFERENCE_PATTERN =", function_start)
if function_start < 0 or function_end < 0:
    raise SystemExit("semantic-audit completion-template function block not found")
audit = audit[:function_start] + audit[function_end + 1:]
audit = audit.replace("    check_completion_report_template(errors)\n", "")
audit = audit.replace(PAYLOAD["audit_readme_block"], "")
script_allowlist_start = audit.find(
    '    "scripts/relaylm_mvp_completion_report_smoke.py": ('
)
if script_allowlist_start >= 0:
    script_allowlist_end = audit.find("\n    ),", script_allowlist_start)
    if script_allowlist_end < 0:
        raise SystemExit("semantic-audit completion-report allowlist block is unterminated")
    audit = (
        audit[:script_allowlist_start]
        + audit[script_allowlist_end + len("\n    ),"):]
    )
for forbidden in (
    "check_completion_report_template",
    "CANONICAL_COMPLETION_REPORT_TEMPLATE_PATH",
    "RETIRED_TEMPLATE_PATHS",
    "implementation-completion-report.md",
):
    if forbidden in audit:
        raise SystemExit(f"semantic audit still owns completion template: {forbidden}")
write("scripts/relaylm_docs_semantic_audit.py", audit)

transitional_path = ROOT / "records/documentation/transitional-assets.json"
transitional = json.loads(transitional_path.read_text(encoding="utf-8"))
families = [
    family
    for family in transitional["families"]
    if family.get("family_id") != "legacy-completion-report-validation"
]
families.append(
    {
        "family_id": "legacy-completion-report-validation",
        "paths": sorted(
            [
                ".github/workflows/documentation-completion-report-files.yml",
                "docs/evidence/implementation/README.md",
                "docs/evidence/implementation/*_completion_report.md",
                "scripts/relaylm_mvp_completion_report_smoke.py",
            ]
        ),
        "owner": "documentation",
        "protected_boundary": (
            "Structural integrity of already-committed completion reports: accepted "
            "historical metadata profiles, required sections, concrete source-PR evidence, "
            "and unresolved-placeholder rejection. This family owns no model, template, "
            "current-status, architecture, contract, or new-report creation authority."
        ),
        "current_consumers": sorted(
            [
                ".github/workflows/documentation-completion-report-files.yml",
                ".github/workflows/wave4-cross-slice-convergence.yml",
                ".github/workflows/wave5-cross-slice-convergence.yml",
                "scripts/relaylm_ci_consolidated_smoke.py",
                "scripts/relaylm_mvp_eval_runner_registry.py",
            ]
        ),
        "removal_gate": (
            "Every existing completion report has a reviewed D2-D6 synthesis, allowlisted "
            "record classification, or Git-retirement disposition; no workflow, consolidated "
            "smoke group, current architecture procedure, or operator consumes the validator; "
            "and generic authority, links, record, and Git-recoverability validation protects "
            "every continuing invariant."
        ),
        "replacement_validation": sorted(
            [
                "active_document_authority",
                "git_recoverability",
                "links_and_routers",
                "retained_record_allowlist",
            ]
        ),
        "growth_policy": "closed",
    }
)
transitional["families"] = sorted(families, key=lambda item: item["family_id"])
transitional_path.write_text(
    json.dumps(transitional, indent=2, ensure_ascii=False) + "\n",
    encoding="utf-8",
)

manifest_path = ROOT / "records/documentation/retirement-manifest.json"
manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
entries = [
    entry
    for entry in manifest["entries"]
    if entry.get("old_path") != "docs/templates/implementation-completion-report.md"
]
entries.append(
    {
        "old_path": "docs/templates/implementation-completion-report.md",
        "last_live_commit": "28176f4a8336b6ce7191166e1c720cb71a617e99",
        "old_blob_sha": "f6b1df5d39d0c67b4183ec9b21be302fde81147b",
        "removed_by_pr": 670,
        "replacement_paths": sorted(
            [
                "docs/DOCUMENTATION_MODEL.md",
                "docs/contracts/documentation-governance.md",
            ]
        ),
        "disposition": "superseded",
        "retention_reason": (
            "D1 superseded the reusable per-implementation completion-report creation model "
            "with PR-body evidence and narrowly allowlisted retained records. Existing reports "
            "remain a closed transitional family; the former template is recoverable from Git."
        ),
    }
)
manifest["entries"] = sorted(entries, key=lambda item: item["old_path"])
manifest_path.write_text(
    json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
    encoding="utf-8",
)

model = read("docs/DOCUMENTATION_MODEL.md")
model = replace_once(
    model,
    PAYLOAD["model_old"],
    PAYLOAD["model_new"],
    "documentation model completion retirement",
)
write("docs/DOCUMENTATION_MODEL.md", model)

contract = read("docs/contracts/documentation-governance.md")
contract = replace_once(
    contract,
    PAYLOAD["contract_marker"],
    PAYLOAD["contract_replacement"],
    "governance completion compatibility",
)
write("docs/contracts/documentation-governance.md", contract)

live_paths = [
    ".github",
    "scripts",
    "docs/README.md",
    "docs/DOCUMENTATION_MODEL.md",
    "docs/evidence/implementation/README.md",
    "docs/templates/README.md",
    "docs/contracts/documentation-governance.md",
]
for relative in live_paths:
    path = ROOT / relative
    candidates = [path] if path.is_file() else [
        candidate for candidate in path.rglob("*") if candidate.is_file()
    ]
    for candidate in candidates:
        try:
            body = candidate.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        if "--check-model" in body:
            raise SystemExit(
                f"live --check-model reference remains: {candidate.relative_to(ROOT)}"
            )
if (ROOT / "docs/templates/implementation-completion-report.md").exists():
    raise SystemExit("retired completion-report template remains")
if (ROOT / ".github/workflows/documentation-completion-report-model.yml").exists():
    raise SystemExit("retired completion-report model workflow remains")
