import RelayTheory.AdmissibilityEfficacyQuotient

namespace RelayTheory

namespace FinKernel

/--
Extensional inclusion of generated admissibility domains.  This compares the
finite sequential closures themselves, not the literal generator lists.
-/
def GeneratedDomainLe {n : Nat}
    (K L : FutureContextFamily n) : Prop :=
  ∀ c : FinKernel n n, GeneratedContext K c → GeneratedContext L c

/-- Strict generated-domain expansion. -/
def GeneratedDomainLt {n : Nat}
    (K L : FutureContextFamily n) : Prop :=
  GeneratedDomainLe K L ∧ ¬ GeneratedDomainLe L K

end FinKernel

/-- Generated-domain inclusion is reflexive. -/
theorem finKernel_generatedDomainLe_refl {n : Nat}
    (K : FinKernel.FutureContextFamily n) :
    FinKernel.GeneratedDomainLe K K := by
  intro c hc
  exact hc

/-- Generated-domain inclusion is transitive. -/
theorem finKernel_generatedDomainLe_trans {n : Nat}
    {K L M : FinKernel.FutureContextFamily n}
    (hKL : FinKernel.GeneratedDomainLe K L)
    (hLM : FinKernel.GeneratedDomainLe L M) :
    FinKernel.GeneratedDomainLe K M := by
  intro c hc
  exact hLM c (hKL c hc)

/-- Generated-domain equality gives inclusion in both directions. -/
theorem finKernel_generatedDomainEq_iff_mutual_generatedDomainLe {n : Nat}
    {K L : FinKernel.FutureContextFamily n} :
    FinKernel.GeneratedDomainEq K L ↔
      FinKernel.GeneratedDomainLe K L ∧ FinKernel.GeneratedDomainLe L K := by
  constructor
  · intro hEq
    constructor
    · intro c hc
      exact (hEq c).1 hc
    · intro c hc
      exact (hEq c).2 hc
  · rintro ⟨hKL, hLK⟩
    intro c
    exact ⟨hKL c, hLK c⟩

/--
Contextual action equivalence is antitone in admissible future access: if two
actions remain equivalent under the larger generated domain `L`, they remain
equivalent after restricting to the smaller generated domain `K`.
-/
theorem finKernel_contextualActionEq_restrict_generatedDomain {n : Nat}
    {P : FinKernel.ProbeFamily n}
    {K L : FinKernel.FutureContextFamily n}
    {k l : FinKernel n n}
    (hKL : FinKernel.GeneratedDomainLe K L)
    (hEq : FinKernel.ContextualActionEq P L k l) :
    FinKernel.ContextualActionEq P K k l := by
  intro c hc
  exact hEq c (hKL c hc)

/-- Complete full-future response equality restricts along generated-domain inclusion. -/
theorem finKernel_fullFutureResponseEq_restrict_generatedDomain {n : Nat}
    {P : FinKernel.ProbeFamily n}
    {K L : FinKernel.FutureContextFamily n}
    {k l : FinKernel n n}
    (hKL : FinKernel.GeneratedDomainLe K L)
    (hEq : FinKernel.FullFutureResponseEq P L k l) :
    FinKernel.FullFutureResponseEq P K k l := by
  intro c hc m f obs hobs x z
  exact hEq c (hKL c hc) m f obs hobs x z

/--
Contrapositive operational form: enlarging the generated admissibility domain
cannot merge an action distinction that was already visible under the smaller
domain.
-/
theorem finKernel_contextual_distinction_monotone_under_generatedDomainLe
    {n : Nat}
    {P : FinKernel.ProbeFamily n}
    {K L : FinKernel.FutureContextFamily n}
    {k l : FinKernel n n}
    (hKL : FinKernel.GeneratedDomainLe K L)
    (hNot : ¬ FinKernel.ContextualActionEq P K k l) :
    ¬ FinKernel.ContextualActionEq P L k l := by
  intro hLarge
  exact hNot (finKernel_contextualActionEq_restrict_generatedDomain hKL hLarge)

/-- The no-generator closure is strictly contained in the safe merge01 closure. -/
theorem finKernel_merge01_empty_lt_safe_generatedDomain :
    FinKernel.GeneratedDomainLt
      (FinKernel.emptyFutureContextFamily 3)
      FinKernel.merge01SafeContextFamily3 := by
  constructor
  · intro c hc
    have hId := (finKernel_generatedContext_empty_iff_identity).1 hc
    subst c
    exact FinKernel.GeneratedContext.identity
  · intro hBack
    have hCollapseEmpty := hBack
      (FinKernel.dirac finCollapseHidden3)
      finKernel_merge01_collapse_generated_safe
    have hLiteral := (finKernel_generatedContext_empty_iff_identity).1 hCollapseEmpty
    exact finKernel_identity3_ne_hidden_collapse hLiteral.symm

/-- Every safe generated context is also generated by the expanded merge01 policy. -/
theorem finKernel_merge01_safe_le_expanded_generatedDomain :
    FinKernel.GeneratedDomainLe
      FinKernel.merge01SafeContextFamily3
      FinKernel.merge01ExpandedContextFamily3 := by
  intro c hc
  apply finKernel_generatedContext_lift_generators
    (K := FinKernel.merge01SafeContextFamily3)
    (L := FinKernel.merge01ExpandedContextFamily3)
  · intro k hk
    apply FinKernel.GeneratedContext.generator
    unfold FinKernel.merge01SafeContextFamily3 at hk
    unfold FinKernel.merge01ExpandedContextFamily3
    exact Or.inl hk
  · exact hc

/-- The expanded distinguishing move is not generated by the safe closure. -/
theorem finKernel_merge01_move_not_generated_safe :
    ¬ FinKernel.GeneratedContext
      FinKernel.merge01SafeContextFamily3
      finKernelMoveOneToTwo := by
  intro hSafe
  rcases finKernel_merge01_safe_generated_eq_identity_or_collapse hSafe with
    hId | hCollapse
  · apply finKernel_merge01_move_not_collapse_action_eq
    rw [hId]
    exact finKernel_contextActionEq_symm
      finKernel_merge01_collapse_identity_action_eq
  · apply finKernel_merge01_move_not_collapse_action_eq
    rw [hCollapse]
    exact finKernel_contextActionEq_refl
      FinKernel.merge01ProbeFamily3
      (FinKernel.dirac finCollapseHidden3)

/-- The safe generated domain is strictly contained in the expanded domain. -/
theorem finKernel_merge01_safe_lt_expanded_generatedDomain :
    FinKernel.GeneratedDomainLt
      FinKernel.merge01SafeContextFamily3
      FinKernel.merge01ExpandedContextFamily3 := by
  refine ⟨finKernel_merge01_safe_le_expanded_generatedDomain, ?_⟩
  intro hBack
  exact finKernel_merge01_move_not_generated_safe
    (hBack finKernelMoveOneToTwo
      finKernel_merge01_move_generated_by_expanded_policy)

/--
Proper access expansion can be operationally silent: the empty and safe merge01
frames have different generated domains but equivalent reachable dynamics.
-/
theorem finKernel_merge01_empty_safe_silent_proper_expansion :
    FinKernel.GeneratedDomainLt
        (FinKernel.emptyFutureContextFamily 3)
        FinKernel.merge01SafeContextFamily3 ∧
    FinKernel.AccessEfficacyEq
        FinKernel.merge01ProbeFamily3
        (FinKernel.emptyFutureContextFamily 3)
        FinKernel.merge01SafeContextFamily3 := by
  exact ⟨finKernel_merge01_empty_lt_safe_generatedDomain,
    finKernel_merge01_empty_safe_accessEfficacyEq⟩

/--
Proper access expansion can also be strictly distinguishing: safe merge01 keeps
collapse and identity merged, while expanded access splits them.
-/
theorem finKernel_merge01_safe_expanded_effective_proper_expansion :
    FinKernel.GeneratedDomainLt
        FinKernel.merge01SafeContextFamily3
        FinKernel.merge01ExpandedContextFamily3 ∧
    FinKernel.ContextualActionEq
        FinKernel.merge01ProbeFamily3
        FinKernel.merge01SafeContextFamily3
        (FinKernel.dirac finCollapseHidden3)
        (FinKernel.identity 3) ∧
    ¬ FinKernel.ContextualActionEq
        FinKernel.merge01ProbeFamily3
        FinKernel.merge01ExpandedContextFamily3
        (FinKernel.dirac finCollapseHidden3)
        (FinKernel.identity 3) := by
  exact ⟨finKernel_merge01_safe_lt_expanded_generatedDomain,
    finKernel_merge01_collapse_identity_contextual_action_eq_safe,
    finKernel_merge01_collapse_identity_not_contextual_action_eq_expanded⟩

/-- Acceptance bundle for #2853 access-refinement monotonicity. -/
theorem finKernel_access_refinement_monotonicity_bundle :
    (∀ {n : Nat}
      {P : FinKernel.ProbeFamily n}
      {K L : FinKernel.FutureContextFamily n}
      {k l : FinKernel n n},
      FinKernel.GeneratedDomainLe K L →
      FinKernel.ContextualActionEq P L k l →
      FinKernel.ContextualActionEq P K k l) ∧
    (FinKernel.GeneratedDomainLt
        (FinKernel.emptyFutureContextFamily 3)
        FinKernel.merge01SafeContextFamily3 ∧
      FinKernel.AccessEfficacyEq
        FinKernel.merge01ProbeFamily3
        (FinKernel.emptyFutureContextFamily 3)
        FinKernel.merge01SafeContextFamily3) ∧
    (FinKernel.GeneratedDomainLt
        FinKernel.merge01SafeContextFamily3
        FinKernel.merge01ExpandedContextFamily3 ∧
      FinKernel.ContextualActionEq
        FinKernel.merge01ProbeFamily3
        FinKernel.merge01SafeContextFamily3
        (FinKernel.dirac finCollapseHidden3)
        (FinKernel.identity 3) ∧
      ¬ FinKernel.ContextualActionEq
        FinKernel.merge01ProbeFamily3
        FinKernel.merge01ExpandedContextFamily3
        (FinKernel.dirac finCollapseHidden3)
        (FinKernel.identity 3)) := by
  exact ⟨finKernel_contextualActionEq_restrict_generatedDomain,
    finKernel_merge01_empty_safe_silent_proper_expansion,
    finKernel_merge01_safe_expanded_effective_proper_expansion⟩

end RelayTheory
