import RelayTheory.SequentialContextCongruence

namespace RelayTheory

namespace FinKernel

/--
Finite sequential closure generated by a declared family of endomorphic future
contexts.  Identity is available without being listed as a generator, and
already-generated contexts may be composed in execution order.
-/
inductive GeneratedContext {n : Nat}
    (K : FutureContextFamily n) : FinKernel n n → Prop where
  | identity : GeneratedContext K (identity n)
  | generator {k : FinKernel n n} : K k → GeneratedContext K k
  | seq {k l : FinKernel n n} :
      GeneratedContext K k →
      GeneratedContext K l →
      GeneratedContext K (compose l k)

end FinKernel

/--
If every generator of `K` is already in the sequential closure generated by
`L`, then every finite context generated by `K` is in the closure generated by
`L`.
-/
theorem finKernel_generatedContext_lift_generators
    {n : Nat}
    {K L : FinKernel.FutureContextFamily n}
    (hgen : ∀ c : FinKernel n n, K c → FinKernel.GeneratedContext L c)
    {c : FinKernel n n}
    (hc : FinKernel.GeneratedContext K c) :
    FinKernel.GeneratedContext L c := by
  induction hc with
  | identity =>
      exact FinKernel.GeneratedContext.identity
  | generator hk =>
      exact hgen _ hk
  | seq hk hl ihk ihl =>
      exact FinKernel.GeneratedContext.seq ihk ihl

/--
Generator-level stability of context-action equivalence is enough for every
finite sequential context generated from those generators.
-/
theorem finKernel_contextActionEq_preserved_by_generated
    {n : Nat}
    {P : FinKernel.ProbeFamily n}
    {K : FinKernel.FutureContextFamily n}
    (hStable : FinKernel.ContextActionEqStableUnder P K)
    {c : FinKernel n n}
    (hc : FinKernel.GeneratedContext K c) :
    ∀ {k l : FinKernel n n},
      FinKernel.ContextActionEq P k l →
      FinKernel.ContextActionEq P
        (FinKernel.compose c k)
        (FinKernel.compose c l) := by
  induction hc with
  | identity =>
      intro k l hkl
      simpa only [finKernel_compose_identity_after] using hkl
  | generator hmem =>
      intro k l hkl m f
      exact (hStable k l hkl _ hmem) f
  | seq hk hl ihk ihl =>
      intro k l hkl
      have hFirst := ihk hkl
      have hSecond := ihl hFirst
      simpa only [finKernel_compose_associative] using hSecond

/--
Equivalently, a relation stable under the declared generators is stable under
the entire finite sequential closure generated by them.
-/
theorem finKernel_contextActionEq_stable_under_generated
    {n : Nat}
    {P : FinKernel.ProbeFamily n}
    {K : FinKernel.FutureContextFamily n}
    (hStable : FinKernel.ContextActionEqStableUnder P K) :
    FinKernel.ContextActionEqStableUnder P
      (FinKernel.GeneratedContext K) := by
  intro k l hkl c hc
  exact finKernel_contextActionEq_preserved_by_generated hStable hc hkl

/--
Every collapse-only generator is also a collapse-plus-identity generated
context.
-/
theorem finKernel_merge01_collapseOnly_generated_in_collapseIdentity
    {c : FinKernel 3 3}
    (hc : FinKernel.GeneratedContext
      FinKernel.merge01CollapseOnlyContextFamily3 c) :
    FinKernel.GeneratedContext
      FinKernel.merge01CollapseIdentityContextFamily3 c := by
  apply finKernel_generatedContext_lift_generators
    (K := FinKernel.merge01CollapseOnlyContextFamily3)
    (L := FinKernel.merge01CollapseIdentityContextFamily3)
  · intro k hk
    apply FinKernel.GeneratedContext.generator
    unfold FinKernel.merge01CollapseOnlyContextFamily3 at hk
    unfold FinKernel.merge01CollapseIdentityContextFamily3
    exact Or.inl hk
  · exact hc

/--
Conversely, the explicit identity generator adds nothing to generated closure:
identity is already present by the closure constructor.
-/
theorem finKernel_merge01_collapseIdentity_generated_in_collapseOnly
    {c : FinKernel 3 3}
    (hc : FinKernel.GeneratedContext
      FinKernel.merge01CollapseIdentityContextFamily3 c) :
    FinKernel.GeneratedContext
      FinKernel.merge01CollapseOnlyContextFamily3 c := by
  apply finKernel_generatedContext_lift_generators
    (K := FinKernel.merge01CollapseIdentityContextFamily3)
    (L := FinKernel.merge01CollapseOnlyContextFamily3)
  · intro k hk
    unfold FinKernel.merge01CollapseIdentityContextFamily3 at hk
    rcases hk with hk | hk
    · apply FinKernel.GeneratedContext.generator
      unfold FinKernel.merge01CollapseOnlyContextFamily3
      exact hk
    · rw [hk]
      exact FinKernel.GeneratedContext.identity
  · exact hc

/--
The literally different collapse-only and collapse-plus-identity generator
families generate exactly the same finite sequential continuation closure.
-/
theorem finKernel_merge01_generated_context_policy_iff
    (c : FinKernel 3 3) :
    FinKernel.GeneratedContext
        FinKernel.merge01CollapseOnlyContextFamily3 c ↔
      FinKernel.GeneratedContext
        FinKernel.merge01CollapseIdentityContextFamily3 c := by
  constructor
  · exact finKernel_merge01_collapseOnly_generated_in_collapseIdentity
  · exact finKernel_merge01_collapseIdentity_generated_in_collapseOnly

/-- The expanded policy's distinguishing move is present in its generated closure. -/
theorem finKernel_merge01_move_generated_by_expanded_policy :
    FinKernel.GeneratedContext
      FinKernel.merge01ExpandedContextFamily3
      finKernelMoveOneToTwo := by
  apply FinKernel.GeneratedContext.generator
  exact Or.inr rfl

/--
The safe collapse-only continuation policy remains congruence-stable after
closing it under arbitrary finite sequential composition.
-/
theorem finKernel_merge01_contextActionEq_stable_under_safe_generated :
    FinKernel.ContextActionEqStableUnder
      FinKernel.merge01ProbeFamily3
      (FinKernel.GeneratedContext FinKernel.merge01SafeContextFamily3) := by
  exact finKernel_contextActionEq_stable_under_generated
    finKernel_merge01_contextActionEq_stable_under_safe_policy

/--
The expanded policy remains non-congruent after generated closure.  Passing from
its literal generator family to finite sequential closure cannot erase the
already-admitted distinguishing generator.
-/
theorem finKernel_merge01_contextActionEq_not_stable_under_expanded_generated :
    ¬ FinKernel.ContextActionEqStableUnder
      FinKernel.merge01ProbeFamily3
      (FinKernel.GeneratedContext FinKernel.merge01ExpandedContextFamily3) := by
  intro hStableGenerated
  apply finKernel_merge01_contextActionEq_not_stable_under_expanded_policy
  intro k l hkl c hc
  exact hStableGenerated k l hkl c
    (FinKernel.GeneratedContext.generator hc)

/--
Acceptance bundle: generator-level stability lifts to finite sequential closure;
literally distinct collapse-only and collapse-plus-identity generator families
have the same generated closure; and the distinguishing expanded policy remains
non-stable after closure.
-/
theorem finKernel_generated_continuation_closure_bundle :
    (∀ c : FinKernel 3 3,
      FinKernel.GeneratedContext
          FinKernel.merge01CollapseOnlyContextFamily3 c ↔
        FinKernel.GeneratedContext
          FinKernel.merge01CollapseIdentityContextFamily3 c) ∧
    FinKernel.ContextActionEqStableUnder
      FinKernel.merge01ProbeFamily3
      (FinKernel.GeneratedContext FinKernel.merge01SafeContextFamily3) ∧
    ¬ FinKernel.ContextActionEqStableUnder
      FinKernel.merge01ProbeFamily3
      (FinKernel.GeneratedContext FinKernel.merge01ExpandedContextFamily3) := by
  exact ⟨finKernel_merge01_generated_context_policy_iff,
    finKernel_merge01_contextActionEq_stable_under_safe_generated,
    finKernel_merge01_contextActionEq_not_stable_under_expanded_generated⟩

end RelayTheory
