import RelayTheory.GeneratedClassCoveragePreorder

namespace RelayTheory

/-- A second nontrivial idempotent collapse on `Fin 3`: keep state 1 and collapse 0/2 to 0. -/
def finCollapseOther3 (x : Fin 3) : Fin 3 :=
  if x = (1 : Fin 3) then (1 : Fin 3) else (0 : Fin 3)

namespace FinKernel

/-- Singleton future-context family generated by the second idempotent collapse. -/
def otherCollapseContextFamily3 : FutureContextFamily 3 :=
  fun k => k = dirac finCollapseOther3

/-- Fixed exact residual state for the existing hidden collapse under all probes. -/
def hiddenCollapseResidualExact3 :
    FullFutureResponseSpace (allProbes 3) merge01SafeContextFamily3 :=
  IdentityResidualState
    (allProbes 3)
    merge01SafeContextFamily3
    (dirac finCollapseHidden3)
    finKernel_merge01_collapse_generated_safe

/-- Fixed exact residual state for the second collapse under all probes. -/
def otherCollapseResidualExact3 :
    FullFutureResponseSpace (allProbes 3) otherCollapseContextFamily3 :=
  IdentityResidualState
    (allProbes 3)
    otherCollapseContextFamily3
    (dirac finCollapseOther3)
    (GeneratedContext.generator rfl)

/-- Root-preserving class-relabeling relation between the two two-state residual systems. -/
def RelabeledIdempotentDynamicsRel3
    (s : FullFutureResponseSpace (allProbes 3) merge01SafeContextFamily3)
    (t : FullFutureResponseSpace (allProbes 3) otherCollapseContextFamily3) : Prop :=
  (FullFutureResponseSpaceEq s
      (ResidualIdentityState (allProbes 3) merge01SafeContextFamily3) ∧
    FullFutureResponseSpaceEq t
      (ResidualIdentityState (allProbes 3) otherCollapseContextFamily3)) ∨
  (FullFutureResponseSpaceEq s hiddenCollapseResidualExact3 ∧
    FullFutureResponseSpaceEq t otherCollapseResidualExact3)

end FinKernel

/-- The second collapse is not the identity function. -/
theorem finCollapseOther3_ne_identity :
    finCollapseOther3 ≠ (fun x : Fin 3 => x) := by
  intro h
  have hv := congrFun h (2 : Fin 3)
  simp [finCollapseOther3] at hv

/-- The two deterministic collapses are literally different. -/
theorem finCollapseOther3_ne_hidden :
    finCollapseOther3 ≠ finCollapseHidden3 := by
  intro h
  have hv := congrFun h (1 : Fin 3)
  simp [finCollapseOther3, finCollapseHidden3, finSelectorAt] at hv

/-- The second collapse is distinct from identity as an exact kernel. -/
theorem finKernel_identity3_ne_other_collapse :
    FinKernel.identity 3 ≠ FinKernel.dirac finCollapseOther3 := by
  intro h
  have hv := congrArg
    (fun k => k (2 : Fin 3) (2 : Fin 3)) h
  simp [FinKernel.identity, FinKernel.dirac, finCollapseOther3] at hv

/-- The two collapse kernels are literally distinct. -/
theorem finKernel_hidden_collapse_ne_other_collapse :
    FinKernel.dirac finCollapseHidden3 ≠
      FinKernel.dirac finCollapseOther3 := by
  intro h
  have hv := congrArg
    (fun k => k (1 : Fin 3) (1 : Fin 3)) h
  simp [FinKernel.dirac, finCollapseHidden3, finCollapseOther3,
    finSelectorAt] at hv

/-- The second deterministic collapse is idempotent as an exact kernel. -/
theorem finKernel_otherCollapse_idempotent :
    FinKernel.compose
        (FinKernel.dirac finCollapseOther3)
        (FinKernel.dirac finCollapseOther3) =
      FinKernel.dirac finCollapseOther3 := by
  rw [finKernel_dirac_compose]
  apply finKernel_dirac_congr
  intro x
  by_cases h1 : x = (1 : Fin 3)
  · subst x
    simp [finCollapseOther3]
  · simp [finCollapseOther3, h1]

/-- The second collapse is generated by its singleton policy. -/
theorem finKernel_other_collapse_generated :
    FinKernel.GeneratedContext
      FinKernel.otherCollapseContextFamily3
      (FinKernel.dirac finCollapseOther3) := by
  apply FinKernel.GeneratedContext.generator
  rfl

/-- The second singleton-generated closure contains exactly identity or the second collapse. -/
theorem finKernel_other_generated_eq_identity_or_collapse
    {c : FinKernel 3 3}
    (hc : FinKernel.GeneratedContext FinKernel.otherCollapseContextFamily3 c) :
    c = FinKernel.identity 3 ∨
      c = FinKernel.dirac finCollapseOther3 := by
  induction hc with
  | identity => exact Or.inl rfl
  | generator hk => exact Or.inr hk
  | seq hk hl ihk ihl =>
      rcases ihk with hik | hck
      · rcases ihl with hil | hcl
        · left
          rw [hik, hil]
          simp only [finKernel_compose_identity_after]
        · right
          rw [hik, hcl]
          simp only [finKernel_compose_identity_before]
      · rcases ihl with hil | hcl
        · right
          rw [hck, hil]
          simp only [finKernel_compose_identity_after]
        · right
          rw [hck, hcl]
          exact finKernel_otherCollapse_idempotent

/-- Under all probes, the existing collapse class cannot be covered by the second frame. -/
theorem finKernel_allProbes_safe_other_not_generatedClassCovered :
    ¬ FinKernel.GeneratedClassCovered
      (FinKernel.allProbes 3)
      FinKernel.merge01SafeContextFamily3
      FinKernel.otherCollapseContextFamily3 := by
  intro hCover
  rcases hCover
      (FinKernel.dirac finCollapseHidden3)
      finKernel_merge01_collapse_generated_safe with
    ⟨l, hl, hEq⟩
  have hLiteral : FinKernel.dirac finCollapseHidden3 = l :=
    (finKernel_contextualActionEq_allProbes_iff_eq
      FinKernel.merge01SafeContextFamily3
      (FinKernel.dirac finCollapseHidden3) l).1 hEq
  rcases finKernel_other_generated_eq_identity_or_collapse hl with hId | hOther
  · exact finKernel_identity3_ne_hidden_collapse
      (hLiteral.trans hId).symm
  · exact finKernel_hidden_collapse_ne_other_collapse
      (hLiteral.trans hOther)

/-- Conversely, the second collapse class cannot be covered by the existing safe frame. -/
theorem finKernel_allProbes_other_safe_not_generatedClassCovered :
    ¬ FinKernel.GeneratedClassCovered
      (FinKernel.allProbes 3)
      FinKernel.otherCollapseContextFamily3
      FinKernel.merge01SafeContextFamily3 := by
  intro hCover
  rcases hCover
      (FinKernel.dirac finCollapseOther3)
      finKernel_other_collapse_generated with
    ⟨l, hl, hEq⟩
  have hLiteral : FinKernel.dirac finCollapseOther3 = l :=
    (finKernel_contextualActionEq_allProbes_iff_eq
      FinKernel.otherCollapseContextFamily3
      (FinKernel.dirac finCollapseOther3) l).1 hEq
  rcases finKernel_merge01_safe_generated_eq_identity_or_collapse hl with hId | hHidden
  · exact finKernel_identity3_ne_other_collapse
      (hLiteral.trans hId).symm
  · exact finKernel_hidden_collapse_ne_other_collapse
      (hLiteral.trans hHidden).symm

/-- Hence the two frames do not have the same realized contextual-class support. -/
theorem finKernel_allProbes_safe_other_not_accessClassSupportEq :
    ¬ FinKernel.AccessClassSupportEq
      (FinKernel.allProbes 3)
      FinKernel.merge01SafeContextFamily3
      FinKernel.otherCollapseContextFamily3 := by
  intro h
  exact finKernel_allProbes_safe_other_not_generatedClassCovered h.2.1

/-- Under all probes, root and any distinct generated literal action give distinct residual states. -/
theorem finKernel_allProbes_root_ne_generatedResidual {n : Nat}
    {K : FinKernel.FutureContextFamily n}
    {c : FinKernel n n}
    (hc : FinKernel.GeneratedContext K c)
    (hne : FinKernel.identity n ≠ c) :
    ¬ FinKernel.FullFutureResponseSpaceEq
      (FinKernel.ResidualIdentityState (FinKernel.allProbes n) K)
      (FinKernel.IdentityResidualState (FinKernel.allProbes n) K c hc) := by
  intro hResidual
  change FinKernel.IdentityResidualStateEq
    (FinKernel.allProbes n) K
    (FinKernel.identity n) c
    FinKernel.GeneratedContext.identity hc at hResidual
  have hAction : FinKernel.ContextualActionEq
      (FinKernel.allProbes n) K (FinKernel.identity n) c :=
    (finKernel_identityResidualStateEq_iff_contextualActionEq
      FinKernel.GeneratedContext.identity hc).1 hResidual
  exact hne
    ((finKernel_contextualActionEq_allProbes_iff_eq
      K (FinKernel.identity n) c).1 hAction)

/-- Root and hidden-collapse residuals are distinct under all exact probes. -/
theorem finKernel_allProbes_safe_root_ne_hiddenResidual :
    ¬ FinKernel.FullFutureResponseSpaceEq
      (FinKernel.ResidualIdentityState
        (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3)
      FinKernel.hiddenCollapseResidualExact3 := by
  simpa [FinKernel.hiddenCollapseResidualExact3] using
    (finKernel_allProbes_root_ne_generatedResidual
      (K := FinKernel.merge01SafeContextFamily3)
      finKernel_merge01_collapse_generated_safe
      finKernel_identity3_ne_hidden_collapse)

/-- Root and second-collapse residuals are distinct under all exact probes. -/
theorem finKernel_allProbes_other_root_ne_collapseResidual :
    ¬ FinKernel.FullFutureResponseSpaceEq
      (FinKernel.ResidualIdentityState
        (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3)
      FinKernel.otherCollapseResidualExact3 := by
  simpa [FinKernel.otherCollapseResidualExact3] using
    (finKernel_allProbes_root_ne_generatedResidual
      (K := FinKernel.otherCollapseContextFamily3)
      finKernel_other_collapse_generated
      finKernel_identity3_ne_other_collapse)

/-- Every reachable exact-probe state of the existing safe frame is root or hidden collapse. -/
theorem finKernel_allProbes_safe_reachable_classification
    {s : FinKernel.FullFutureResponseSpace
      (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3}
    (hs : FinKernel.ReachableResidualState
      (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3 s) :
    FinKernel.FullFutureResponseSpaceEq s
        (FinKernel.ResidualIdentityState
          (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3) ∨
      FinKernel.FullFutureResponseSpaceEq s
        FinKernel.hiddenCollapseResidualExact3 := by
  rcases hs with ⟨k, hk, hsk⟩
  rcases finKernel_merge01_safe_generated_eq_identity_or_collapse hk with hId | hCollapse
  · subst k
    left
    have hSame : FinKernel.IdentityResidualStateEq
        (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3
        (FinKernel.identity 3) (FinKernel.identity 3)
        hk FinKernel.GeneratedContext.identity :=
      (finKernel_identityResidualStateEq_iff_contextualActionEq
        hk FinKernel.GeneratedContext.identity).2
        (finKernel_contextualActionEq_refl
          (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3
          (FinKernel.identity 3))
    exact finKernel_fullFutureResponseSpaceEq_trans hsk hSame
  · subst k
    right
    have hSame : FinKernel.IdentityResidualStateEq
        (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3
        (FinKernel.dirac finCollapseHidden3)
        (FinKernel.dirac finCollapseHidden3)
        hk finKernel_merge01_collapse_generated_safe :=
      (finKernel_identityResidualStateEq_iff_contextualActionEq
        hk finKernel_merge01_collapse_generated_safe).2
        (finKernel_contextualActionEq_refl
          (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3
          (FinKernel.dirac finCollapseHidden3))
    exact finKernel_fullFutureResponseSpaceEq_trans hsk hSame

/-- Every reachable exact-probe state of the second frame is root or its collapse. -/
theorem finKernel_allProbes_other_reachable_classification
    {s : FinKernel.FullFutureResponseSpace
      (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3}
    (hs : FinKernel.ReachableResidualState
      (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3 s) :
    FinKernel.FullFutureResponseSpaceEq s
        (FinKernel.ResidualIdentityState
          (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3) ∨
      FinKernel.FullFutureResponseSpaceEq s
        FinKernel.otherCollapseResidualExact3 := by
  rcases hs with ⟨k, hk, hsk⟩
  rcases finKernel_other_generated_eq_identity_or_collapse hk with hId | hCollapse
  · subst k
    left
    have hSame : FinKernel.IdentityResidualStateEq
        (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3
        (FinKernel.identity 3) (FinKernel.identity 3)
        hk FinKernel.GeneratedContext.identity :=
      (finKernel_identityResidualStateEq_iff_contextualActionEq
        hk FinKernel.GeneratedContext.identity).2
        (finKernel_contextualActionEq_refl
          (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3
          (FinKernel.identity 3))
    exact finKernel_fullFutureResponseSpaceEq_trans hsk hSame
  · subst k
    right
    have hSame : FinKernel.IdentityResidualStateEq
        (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3
        (FinKernel.dirac finCollapseOther3)
        (FinKernel.dirac finCollapseOther3)
        hk finKernel_other_collapse_generated :=
      (finKernel_identityResidualStateEq_iff_contextualActionEq
        hk finKernel_other_collapse_generated).2
        (finKernel_contextualActionEq_refl
          (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3
          (FinKernel.dirac finCollapseOther3))
    exact finKernel_fullFutureResponseSpaceEq_trans hsk hSame

/-- Generic root/root successor has root output. -/
theorem finKernel_successor_root_root_output {n : Nat}
    {P : FinKernel.ProbeFamily n} {K : FinKernel.FutureContextFamily n}
    {s t u : FinKernel.FullFutureResponseSpace P K}
    (hs : FinKernel.FullFutureResponseSpaceEq s
      (FinKernel.ResidualIdentityState P K))
    (ht : FinKernel.FullFutureResponseSpaceEq t
      (FinKernel.ResidualIdentityState P K))
    (hSucc : FinKernel.SourceSubstitutionSuccessorRel P K s t u) :
    FinKernel.FullFutureResponseSpaceEq u
      (FinKernel.ResidualIdentityState P K) := by
  have hRootSig := finKernel_identityResidualState_eq_fullFutureResponse
    (P := P) (K := K) FinKernel.GeneratedContext.identity
  have hsSig := finKernel_fullFutureResponseSpaceEq_trans hs hRootSig
  have htSig := finKernel_fullFutureResponseSpaceEq_trans ht hRootSig
  have huSig := finKernel_sourceSubstitutionSuccessorRel_to_composite_signature
    (P := P) (K := K) FinKernel.GeneratedContext.identity hsSig htSig hSucc
  simp only [finKernel_compose_identity_after] at huSig
  exact finKernel_fullFutureResponseSpaceEq_trans huSig
    (finKernel_fullFutureResponseSpaceEq_symm hRootSig)

/-- Generic root/generated successor has the generated state as output. -/
theorem finKernel_successor_root_generated_output {n : Nat}
    {P : FinKernel.ProbeFamily n} {K : FinKernel.FutureContextFamily n}
    {c : FinKernel n n} (hc : FinKernel.GeneratedContext K c)
    {s t u : FinKernel.FullFutureResponseSpace P K}
    (hs : FinKernel.FullFutureResponseSpaceEq s
      (FinKernel.ResidualIdentityState P K))
    (ht : FinKernel.FullFutureResponseSpaceEq t
      (FinKernel.IdentityResidualState P K c hc))
    (hSucc : FinKernel.SourceSubstitutionSuccessorRel P K s t u) :
    FinKernel.FullFutureResponseSpaceEq u
      (FinKernel.IdentityResidualState P K c hc) := by
  have hRootSig := finKernel_identityResidualState_eq_fullFutureResponse
    (P := P) (K := K) FinKernel.GeneratedContext.identity
  have hCSig := finKernel_identityResidualState_eq_fullFutureResponse
    (P := P) (K := K) hc
  have hsSig := finKernel_fullFutureResponseSpaceEq_trans hs hRootSig
  have htSig := finKernel_fullFutureResponseSpaceEq_trans ht hCSig
  have huSig := finKernel_sourceSubstitutionSuccessorRel_to_composite_signature
    (P := P) (K := K) FinKernel.GeneratedContext.identity hsSig htSig hSucc
  simp only [finKernel_compose_identity_before] at huSig
  exact finKernel_fullFutureResponseSpaceEq_trans huSig
    (finKernel_fullFutureResponseSpaceEq_symm hCSig)

/-- Generic generated/root successor has the generated state as output. -/
theorem finKernel_successor_generated_root_output {n : Nat}
    {P : FinKernel.ProbeFamily n} {K : FinKernel.FutureContextFamily n}
    {c : FinKernel n n} (hc : FinKernel.GeneratedContext K c)
    {s t u : FinKernel.FullFutureResponseSpace P K}
    (hs : FinKernel.FullFutureResponseSpaceEq s
      (FinKernel.IdentityResidualState P K c hc))
    (ht : FinKernel.FullFutureResponseSpaceEq t
      (FinKernel.ResidualIdentityState P K))
    (hSucc : FinKernel.SourceSubstitutionSuccessorRel P K s t u) :
    FinKernel.FullFutureResponseSpaceEq u
      (FinKernel.IdentityResidualState P K c hc) := by
  have hRootSig := finKernel_identityResidualState_eq_fullFutureResponse
    (P := P) (K := K) FinKernel.GeneratedContext.identity
  have hCSig := finKernel_identityResidualState_eq_fullFutureResponse
    (P := P) (K := K) hc
  have hsSig := finKernel_fullFutureResponseSpaceEq_trans hs hCSig
  have htSig := finKernel_fullFutureResponseSpaceEq_trans ht hRootSig
  have huSig := finKernel_sourceSubstitutionSuccessorRel_to_composite_signature
    (P := P) (K := K) hc hsSig htSig hSucc
  simp only [finKernel_compose_identity_after] at huSig
  exact finKernel_fullFutureResponseSpaceEq_trans huSig
    (finKernel_fullFutureResponseSpaceEq_symm hCSig)

/-- Generic idempotent/generated successor has the same generated state as output. -/
theorem finKernel_successor_idempotent_output {n : Nat}
    {P : FinKernel.ProbeFamily n} {K : FinKernel.FutureContextFamily n}
    {c : FinKernel n n} (hc : FinKernel.GeneratedContext K c)
    (hIdem : FinKernel.compose c c = c)
    {s t u : FinKernel.FullFutureResponseSpace P K}
    (hs : FinKernel.FullFutureResponseSpaceEq s
      (FinKernel.IdentityResidualState P K c hc))
    (ht : FinKernel.FullFutureResponseSpaceEq t
      (FinKernel.IdentityResidualState P K c hc))
    (hSucc : FinKernel.SourceSubstitutionSuccessorRel P K s t u) :
    FinKernel.FullFutureResponseSpaceEq u
      (FinKernel.IdentityResidualState P K c hc) := by
  have hCSig := finKernel_identityResidualState_eq_fullFutureResponse
    (P := P) (K := K) hc
  have hsSig := finKernel_fullFutureResponseSpaceEq_trans hs hCSig
  have htSig := finKernel_fullFutureResponseSpaceEq_trans ht hCSig
  have huSig := finKernel_sourceSubstitutionSuccessorRel_to_composite_signature
    (P := P) (K := K) hc hsSig htSig hSucc
  rw [hIdem] at huSig
  exact finKernel_fullFutureResponseSpaceEq_trans huSig
    (finKernel_fullFutureResponseSpaceEq_symm hCSig)

/-- Build a root/root successor at any extensionally root-equal output. -/
theorem finKernel_successor_root_root_of_tags {n : Nat}
    {P : FinKernel.ProbeFamily n} {K : FinKernel.FutureContextFamily n}
    {s t u : FinKernel.FullFutureResponseSpace P K}
    (hs : FinKernel.FullFutureResponseSpaceEq s
      (FinKernel.ResidualIdentityState P K))
    (ht : FinKernel.FullFutureResponseSpaceEq t
      (FinKernel.ResidualIdentityState P K))
    (hu : FinKernel.FullFutureResponseSpaceEq u
      (FinKernel.ResidualIdentityState P K)) :
    FinKernel.SourceSubstitutionSuccessorRel P K s t u := by
  have hsReach : FinKernel.ReachableResidualState P K s :=
    ⟨FinKernel.identity n, FinKernel.GeneratedContext.identity, hs⟩
  have htReach : FinKernel.ReachableResidualState P K t :=
    ⟨FinKernel.identity n, FinKernel.GeneratedContext.identity, ht⟩
  rcases finKernel_sourceSubstitutionSuccessorRel_total_on_reachable hsReach htReach with
    ⟨v, hv, hvReach⟩
  have hvRoot := finKernel_successor_root_root_output hs ht hv
  have hvu := finKernel_fullFutureResponseSpaceEq_trans hvRoot
    (finKernel_fullFutureResponseSpaceEq_symm hu)
  exact finKernel_sourceSubstitutionSuccessorRel_output_congr hvu hv

/-- Build a root/generated successor at any extensionally matching generated output. -/
theorem finKernel_successor_root_generated_of_tags {n : Nat}
    {P : FinKernel.ProbeFamily n} {K : FinKernel.FutureContextFamily n}
    {c : FinKernel n n} (hc : FinKernel.GeneratedContext K c)
    {s t u : FinKernel.FullFutureResponseSpace P K}
    (hs : FinKernel.FullFutureResponseSpaceEq s
      (FinKernel.ResidualIdentityState P K))
    (ht : FinKernel.FullFutureResponseSpaceEq t
      (FinKernel.IdentityResidualState P K c hc))
    (hu : FinKernel.FullFutureResponseSpaceEq u
      (FinKernel.IdentityResidualState P K c hc)) :
    FinKernel.SourceSubstitutionSuccessorRel P K s t u := by
  have hsReach : FinKernel.ReachableResidualState P K s :=
    ⟨FinKernel.identity n, FinKernel.GeneratedContext.identity, hs⟩
  have htReach : FinKernel.ReachableResidualState P K t := ⟨c, hc, ht⟩
  rcases finKernel_sourceSubstitutionSuccessorRel_total_on_reachable hsReach htReach with
    ⟨v, hv, hvReach⟩
  have hvC := finKernel_successor_root_generated_output hc hs ht hv
  have hvu := finKernel_fullFutureResponseSpaceEq_trans hvC
    (finKernel_fullFutureResponseSpaceEq_symm hu)
  exact finKernel_sourceSubstitutionSuccessorRel_output_congr hvu hv

/-- Build a generated/root successor at any extensionally matching generated output. -/
theorem finKernel_successor_generated_root_of_tags {n : Nat}
    {P : FinKernel.ProbeFamily n} {K : FinKernel.FutureContextFamily n}
    {c : FinKernel n n} (hc : FinKernel.GeneratedContext K c)
    {s t u : FinKernel.FullFutureResponseSpace P K}
    (hs : FinKernel.FullFutureResponseSpaceEq s
      (FinKernel.IdentityResidualState P K c hc))
    (ht : FinKernel.FullFutureResponseSpaceEq t
      (FinKernel.ResidualIdentityState P K))
    (hu : FinKernel.FullFutureResponseSpaceEq u
      (FinKernel.IdentityResidualState P K c hc)) :
    FinKernel.SourceSubstitutionSuccessorRel P K s t u := by
  have hsReach : FinKernel.ReachableResidualState P K s := ⟨c, hc, hs⟩
  have htReach : FinKernel.ReachableResidualState P K t :=
    ⟨FinKernel.identity n, FinKernel.GeneratedContext.identity, ht⟩
  rcases finKernel_sourceSubstitutionSuccessorRel_total_on_reachable hsReach htReach with
    ⟨v, hv, hvReach⟩
  have hvC := finKernel_successor_generated_root_output hc hs ht hv
  have hvu := finKernel_fullFutureResponseSpaceEq_trans hvC
    (finKernel_fullFutureResponseSpaceEq_symm hu)
  exact finKernel_sourceSubstitutionSuccessorRel_output_congr hvu hv

/-- Build an idempotent/generated successor at any extensionally matching generated output. -/
theorem finKernel_successor_idempotent_of_tags {n : Nat}
    {P : FinKernel.ProbeFamily n} {K : FinKernel.FutureContextFamily n}
    {c : FinKernel n n} (hc : FinKernel.GeneratedContext K c)
    (hIdem : FinKernel.compose c c = c)
    {s t u : FinKernel.FullFutureResponseSpace P K}
    (hs : FinKernel.FullFutureResponseSpaceEq s
      (FinKernel.IdentityResidualState P K c hc))
    (ht : FinKernel.FullFutureResponseSpaceEq t
      (FinKernel.IdentityResidualState P K c hc))
    (hu : FinKernel.FullFutureResponseSpaceEq u
      (FinKernel.IdentityResidualState P K c hc)) :
    FinKernel.SourceSubstitutionSuccessorRel P K s t u := by
  have hsReach : FinKernel.ReachableResidualState P K s := ⟨c, hc, hs⟩
  have htReach : FinKernel.ReachableResidualState P K t := ⟨c, hc, ht⟩
  rcases finKernel_sourceSubstitutionSuccessorRel_total_on_reachable hsReach htReach with
    ⟨v, hv, hvReach⟩
  have hvC := finKernel_successor_idempotent_output hc hIdem hs ht hv
  have hvu := finKernel_fullFutureResponseSpaceEq_trans hvC
    (finKernel_fullFutureResponseSpaceEq_symm hu)
  exact finKernel_sourceSubstitutionSuccessorRel_output_congr hvu hv

/-- The relabeling relation is total from the existing safe frame. -/
theorem finKernel_relabeledDynamicsRel_total_left
    {s : FinKernel.FullFutureResponseSpace
      (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3}
    (hs : FinKernel.ReachableResidualState
      (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3 s) :
    ∃ t : FinKernel.FullFutureResponseSpace
        (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3,
      FinKernel.ReachableResidualState
        (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3 t ∧
      FinKernel.RelabeledIdempotentDynamicsRel3 s t := by
  rcases finKernel_allProbes_safe_reachable_classification hs with hRoot | hCollapse
  · refine ⟨FinKernel.ResidualIdentityState
      (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3,
      finKernel_residualIdentityState_reachable, ?_⟩
    exact Or.inl ⟨hRoot, finKernel_fullFutureResponseSpaceEq_refl _⟩
  · refine ⟨FinKernel.otherCollapseResidualExact3,
      finKernel_generated_identityResidualState_reachable
        finKernel_other_collapse_generated, ?_⟩
    exact Or.inr ⟨hCollapse, finKernel_fullFutureResponseSpaceEq_refl _⟩

/-- The relabeling relation is total from the second frame. -/
theorem finKernel_relabeledDynamicsRel_total_right
    {t : FinKernel.FullFutureResponseSpace
      (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3}
    (ht : FinKernel.ReachableResidualState
      (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3 t) :
    ∃ s : FinKernel.FullFutureResponseSpace
        (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3,
      FinKernel.ReachableResidualState
        (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3 s ∧
      FinKernel.RelabeledIdempotentDynamicsRel3 s t := by
  rcases finKernel_allProbes_other_reachable_classification ht with hRoot | hCollapse
  · refine ⟨FinKernel.ResidualIdentityState
      (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3,
      finKernel_residualIdentityState_reachable, ?_⟩
    exact Or.inl ⟨finKernel_fullFutureResponseSpaceEq_refl _, hRoot⟩
  · refine ⟨FinKernel.hiddenCollapseResidualExact3,
      finKernel_generated_identityResidualState_reachable
        finKernel_merge01_collapse_generated_safe, ?_⟩
    exact Or.inr ⟨finKernel_fullFutureResponseSpaceEq_refl _, hCollapse⟩

/-- The relabeling relation is functional on the second frame up to response equality. -/
theorem finKernel_relabeledDynamicsRel_right_functional
    {s : FinKernel.FullFutureResponseSpace
      (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3}
    {t u : FinKernel.FullFutureResponseSpace
      (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3}
    (hst : FinKernel.RelabeledIdempotentDynamicsRel3 s t)
    (hsu : FinKernel.RelabeledIdempotentDynamicsRel3 s u) :
    FinKernel.FullFutureResponseSpaceEq t u := by
  rcases hst with hst | hst <;> rcases hsu with hsu | hsu
  · exact finKernel_fullFutureResponseSpaceEq_trans hst.2
      (finKernel_fullFutureResponseSpaceEq_symm hsu.2)
  · have hBad := finKernel_fullFutureResponseSpaceEq_trans
      (finKernel_fullFutureResponseSpaceEq_symm hst.1) hsu.1
    exact False.elim (finKernel_allProbes_safe_root_ne_hiddenResidual hBad)
  · have hBad := finKernel_fullFutureResponseSpaceEq_trans
      (finKernel_fullFutureResponseSpaceEq_symm hsu.1) hst.1
    exact False.elim (finKernel_allProbes_safe_root_ne_hiddenResidual hBad)
  · exact finKernel_fullFutureResponseSpaceEq_trans hst.2
      (finKernel_fullFutureResponseSpaceEq_symm hsu.2)

/-- The relabeling relation is functional on the first frame up to response equality. -/
theorem finKernel_relabeledDynamicsRel_left_functional
    {s u : FinKernel.FullFutureResponseSpace
      (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3}
    {t : FinKernel.FullFutureResponseSpace
      (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3}
    (hst : FinKernel.RelabeledIdempotentDynamicsRel3 s t)
    (hut : FinKernel.RelabeledIdempotentDynamicsRel3 u t) :
    FinKernel.FullFutureResponseSpaceEq s u := by
  rcases hst with hst | hst <;> rcases hut with hut | hut
  · exact finKernel_fullFutureResponseSpaceEq_trans hst.1
      (finKernel_fullFutureResponseSpaceEq_symm hut.1)
  · have hBad := finKernel_fullFutureResponseSpaceEq_trans
      (finKernel_fullFutureResponseSpaceEq_symm hst.2) hut.2
    exact False.elim (finKernel_allProbes_other_root_ne_collapseResidual hBad)
  · have hBad := finKernel_fullFutureResponseSpaceEq_trans
      (finKernel_fullFutureResponseSpaceEq_symm hut.2) hst.2
    exact False.elim (finKernel_allProbes_other_root_ne_collapseResidual hBad)
  · exact finKernel_fullFutureResponseSpaceEq_trans hst.1
      (finKernel_fullFutureResponseSpaceEq_symm hut.1)

/-- Root is related to root. -/
theorem finKernel_relabeledDynamicsRel_root :
    FinKernel.RelabeledIdempotentDynamicsRel3
      (FinKernel.ResidualIdentityState
        (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3)
      (FinKernel.ResidualIdentityState
        (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3) := by
  exact Or.inl ⟨finKernel_fullFutureResponseSpaceEq_refl _,
    finKernel_fullFutureResponseSpaceEq_refl _⟩

/-- The relabeling relation preserves the whole source-substitution successor table. -/
theorem finKernel_relabeledDynamicsRel_successor_forward
    {sK tK uK : FinKernel.FullFutureResponseSpace
      (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3}
    {sL tL uL : FinKernel.FullFutureResponseSpace
      (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3}
    (hsRel : FinKernel.RelabeledIdempotentDynamicsRel3 sK sL)
    (htRel : FinKernel.RelabeledIdempotentDynamicsRel3 tK tL)
    (huRel : FinKernel.RelabeledIdempotentDynamicsRel3 uK uL)
    (hSuccK : FinKernel.SourceSubstitutionSuccessorRel
      (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3 sK tK uK) :
    FinKernel.SourceSubstitutionSuccessorRel
      (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3 sL tL uL := by
  rcases hsRel with hs0 | hs1 <;>
    rcases htRel with ht0 | ht1 <;>
    rcases huRel with hu0 | hu1
  · exact finKernel_successor_root_root_of_tags hs0.2 ht0.2 hu0.2
  · have hExpected := finKernel_successor_root_root_output hs0.1 ht0.1 hSuccK
    have hBad := finKernel_fullFutureResponseSpaceEq_trans
      (finKernel_fullFutureResponseSpaceEq_symm hExpected) hu1.1
    exact False.elim (finKernel_allProbes_safe_root_ne_hiddenResidual hBad)
  · have hExpected := finKernel_successor_root_generated_output
      finKernel_merge01_collapse_generated_safe hs0.1 ht1.1 hSuccK
    have hBad := finKernel_fullFutureResponseSpaceEq_trans
      (finKernel_fullFutureResponseSpaceEq_symm hu0.1) hExpected
    exact False.elim (finKernel_allProbes_safe_root_ne_hiddenResidual hBad)
  · exact finKernel_successor_root_generated_of_tags
      finKernel_other_collapse_generated hs0.2 ht1.2 hu1.2
  · have hExpected := finKernel_successor_generated_root_output
      finKernel_merge01_collapse_generated_safe hs1.1 ht0.1 hSuccK
    have hBad := finKernel_fullFutureResponseSpaceEq_trans
      (finKernel_fullFutureResponseSpaceEq_symm hu0.1) hExpected
    exact False.elim (finKernel_allProbes_safe_root_ne_hiddenResidual hBad)
  · exact finKernel_successor_generated_root_of_tags
      finKernel_other_collapse_generated hs1.2 ht0.2 hu1.2
  · have hExpected := finKernel_successor_idempotent_output
      finKernel_merge01_collapse_generated_safe finKernel_hiddenCollapse_idempotent
      hs1.1 ht1.1 hSuccK
    have hBad := finKernel_fullFutureResponseSpaceEq_trans
      (finKernel_fullFutureResponseSpaceEq_symm hu0.1) hExpected
    exact False.elim (finKernel_allProbes_safe_root_ne_hiddenResidual hBad)
  · exact finKernel_successor_idempotent_of_tags
      finKernel_other_collapse_generated finKernel_otherCollapse_idempotent
      hs1.2 ht1.2 hu1.2

/-- The relabeling relation also reflects the whole source-substitution successor table. -/
theorem finKernel_relabeledDynamicsRel_successor_backward
    {sK tK uK : FinKernel.FullFutureResponseSpace
      (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3}
    {sL tL uL : FinKernel.FullFutureResponseSpace
      (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3}
    (hsRel : FinKernel.RelabeledIdempotentDynamicsRel3 sK sL)
    (htRel : FinKernel.RelabeledIdempotentDynamicsRel3 tK tL)
    (huRel : FinKernel.RelabeledIdempotentDynamicsRel3 uK uL)
    (hSuccL : FinKernel.SourceSubstitutionSuccessorRel
      (FinKernel.allProbes 3) FinKernel.otherCollapseContextFamily3 sL tL uL) :
    FinKernel.SourceSubstitutionSuccessorRel
      (FinKernel.allProbes 3) FinKernel.merge01SafeContextFamily3 sK tK uK := by
  rcases hsRel with hs0 | hs1 <;>
    rcases htRel with ht0 | ht1 <;>
    rcases huRel with hu0 | hu1
  · exact finKernel_successor_root_root_of_tags hs0.1 ht0.1 hu0.1
  · have hExpected := finKernel_successor_root_root_output hs0.2 ht0.2 hSuccL
    have hBad := finKernel_fullFutureResponseSpaceEq_trans
      (finKernel_fullFutureResponseSpaceEq_symm hExpected) hu1.2
    exact False.elim (finKernel_allProbes_other_root_ne_collapseResidual hBad)
  · have hExpected := finKernel_successor_root_generated_output
      finKernel_other_collapse_generated hs0.2 ht1.2 hSuccL
    have hBad := finKernel_fullFutureResponseSpaceEq_trans
      (finKernel_fullFutureResponseSpaceEq_symm hu0.2) hExpected
    exact False.elim (finKernel_allProbes_other_root_ne_collapseResidual hBad)
  · exact finKernel_successor_root_generated_of_tags
      finKernel_merge01_collapse_generated_safe hs0.1 ht1.1 hu1.1
  · have hExpected := finKernel_successor_generated_root_output
      finKernel_other_collapse_generated hs1.2 ht0.2 hSuccL
    have hBad := finKernel_fullFutureResponseSpaceEq_trans
      (finKernel_fullFutureResponseSpaceEq_symm hu0.2) hExpected
    exact False.elim (finKernel_allProbes_other_root_ne_collapseResidual hBad)
  · exact finKernel_successor_generated_root_of_tags
      finKernel_merge01_collapse_generated_safe hs1.1 ht0.1 hu1.1
  · have hExpected := finKernel_successor_idempotent_output
      finKernel_other_collapse_generated finKernel_otherCollapse_idempotent
      hs1.2 ht1.2 hSuccL
    have hBad := finKernel_fullFutureResponseSpaceEq_trans
      (finKernel_fullFutureResponseSpaceEq_symm hu0.2) hExpected
    exact False.elim (finKernel_allProbes_other_root_ne_collapseResidual hBad)
  · exact finKernel_successor_idempotent_of_tags
      finKernel_merge01_collapse_generated_safe finKernel_hiddenCollapse_idempotent
      hs1.1 ht1.1 hu1.1

/-- Explicit root-preserving isomorphism of the two unlabeled reachable successor systems. -/
def finKernel_safe_other_relabeledDynamicsCorrespondence :
    FinKernel.ReachableClassDynamicsCorrespondence
      (FinKernel.allProbes 3)
      FinKernel.merge01SafeContextFamily3
      FinKernel.otherCollapseContextFamily3 := by
  exact {
    rel := FinKernel.RelabeledIdempotentDynamicsRel3
    total_left := finKernel_relabeledDynamicsRel_total_left
    total_right := finKernel_relabeledDynamicsRel_total_right
    right_functional := finKernel_relabeledDynamicsRel_right_functional
    left_functional := finKernel_relabeledDynamicsRel_left_functional
    root := finKernel_relabeledDynamicsRel_root
    successor_forward := finKernel_relabeledDynamicsRel_successor_forward
    successor_backward := finKernel_relabeledDynamicsRel_successor_backward
  }

/-- Main #2877 counterexample: same relational reachable dynamics, different realized class support. -/
theorem finKernel_relationalDynamics_does_not_identify_accessClassSupport :
    Nonempty (FinKernel.ReachableClassDynamicsCorrespondence
      (FinKernel.allProbes 3)
      FinKernel.merge01SafeContextFamily3
      FinKernel.otherCollapseContextFamily3) ∧
    ¬ FinKernel.AccessClassSupportEq
      (FinKernel.allProbes 3)
      FinKernel.merge01SafeContextFamily3
      FinKernel.otherCollapseContextFamily3 := by
  exact ⟨⟨finKernel_safe_other_relabeledDynamicsCorrespondence⟩,
    finKernel_allProbes_safe_other_not_accessClassSupportEq⟩

/-- Therefore the converse of #2864 fails in the current finite exact semantics. -/
theorem finKernel_relationalDynamics_does_not_imply_accessClassSupportEq :
    ¬ (∀ (P : FinKernel.ProbeFamily 3)
        (K L : FinKernel.FutureContextFamily 3),
      Nonempty (FinKernel.ReachableClassDynamicsCorrespondence P K L) →
      FinKernel.AccessClassSupportEq P K L) := by
  intro h
  exact finKernel_allProbes_safe_other_not_accessClassSupportEq
    (h (FinKernel.allProbes 3)
      FinKernel.merge01SafeContextFamily3
      FinKernel.otherCollapseContextFamily3
      ⟨finKernel_safe_other_relabeledDynamicsCorrespondence⟩)

/-- Acceptance bundle for #2877. -/
theorem finKernel_reachable_dynamics_support_identifiability_bundle :
    FinKernel.dirac finCollapseHidden3 ≠ FinKernel.dirac finCollapseOther3 ∧
    ¬ FinKernel.GeneratedClassCovered
      (FinKernel.allProbes 3)
      FinKernel.merge01SafeContextFamily3
      FinKernel.otherCollapseContextFamily3 ∧
    ¬ FinKernel.GeneratedClassCovered
      (FinKernel.allProbes 3)
      FinKernel.otherCollapseContextFamily3
      FinKernel.merge01SafeContextFamily3 ∧
    Nonempty (FinKernel.ReachableClassDynamicsCorrespondence
      (FinKernel.allProbes 3)
      FinKernel.merge01SafeContextFamily3
      FinKernel.otherCollapseContextFamily3) ∧
    ¬ FinKernel.AccessClassSupportEq
      (FinKernel.allProbes 3)
      FinKernel.merge01SafeContextFamily3
      FinKernel.otherCollapseContextFamily3 := by
  exact ⟨finKernel_hidden_collapse_ne_other_collapse,
    finKernel_allProbes_safe_other_not_generatedClassCovered,
    finKernel_allProbes_other_safe_not_generatedClassCovered,
    ⟨finKernel_safe_other_relabeledDynamicsCorrespondence⟩,
    finKernel_allProbes_safe_other_not_accessClassSupportEq⟩

end RelayTheory
