from pathlib import Path

root = Path(__file__).resolve().parents[1]
path = root / "relaylm/relaymem_slp_one_queued_job_runner.py"
text = path.read_text(encoding="utf-8")
old = '''    try:\n        active, checked_claim, active_reasons = _check_active_claim(\n            claimed,\n            queue_root=exact.queue_root,\n            lease_duration_seconds=exact.lease_duration_seconds,\n            renew=False,\n        )\n    except Exception:\n        active = False\n        checked_claim = None\n        active_reasons = ("one_queued_job_claim_revalidation_failed",)\n    checked_record = (\n        checked_claim.durable_record if checked_claim is not None else None\n    )\n    if not active or not _exact_claimed_record(checked_record):\n        reasons = active_reasons or (\n            "one_queued_job_checked_record_invalid"\n            if active\n            else "one_queued_job_claim_not_current"\n        )\n        return _result(\n            "claim_lost_before_rehydrate",\n            exact,\n            claim_attempted=True,\n            claim_performed=True,\n            claim_result=claim,\n            claim_status=claim.status,\n            reasons=reasons,\n        )\n    assert type(checked_record) is dict\n    claimed = dict(checked_record)\n\n'''
new = '''    try:\n        active, _, active_reasons = _check_active_claim(\n            claimed,\n            queue_root=exact.queue_root,\n            lease_duration_seconds=exact.lease_duration_seconds,\n            renew=False,\n        )\n    except Exception:\n        active = False\n        active_reasons = ("one_queued_job_claim_revalidation_failed",)\n    if not active:\n        return _result(\n            "claim_lost_before_rehydrate",\n            exact,\n            claim_attempted=True,\n            claim_performed=True,\n            claim_result=claim,\n            claim_status=claim.status,\n            reasons=active_reasons or ("one_queued_job_claim_not_current",),\n        )\n    # The canonical B3 dry-run fence rereads the durable record and proves that\n    # this exact claimed revision/owner/generation/token is current. Its returned\n    # durable_record is a renewal proposal, so the committed claim record remains\n    # the exact input for C1-5 and C1-2.\n    claimed = dict(claimed)\n\n'''
if old not in text:
    raise SystemExit("claim reread correction anchor missing")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
print("Phase 6-C2 claim reread correction applied.")
