from pathlib import Path

path = Path("tests/unit/test_knowledge_v0.py")
text = path.read_text(encoding="utf-8")
old = '    original = b"Package-authored reference.\n"\n'
new = '    original = b"Package-authored reference.\\n"\n'
count = text.count(old)
if count != 1:
    raise RuntimeError(f"expected one generated bytes-literal match, found {count}")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
